# Generated by Django 6.0.4 on 2026-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
