/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  DetailResponse,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponsePermissionDenied,
  ErrorResponseValidationError,
  InviteMemberRequest,
  PatchedTeam,
  Team,
  TeamBanner,
  TeamInvitation,
  TeamInvitationInbox,
  TeamJoinRequest,
  UpdateTeamBanner2Body,
  UpdateTeamBannerBody
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const listTeams = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Team[]>(
      {url: `http://localhost:8000/api/teams/`, method: 'GET', signal
    },
      options);
    }
  



export const getListTeamsQueryKey = () => {
    return [
    'http:','localhost:8000','api','teams'
    ] as const;
    }

    
export const getListTeamsQueryOptions = <TData = Awaited<ReturnType<typeof listTeams>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeams>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListTeamsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeams>>> = ({ signal }) => listTeams(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeams>>, TError, TData> 
}

export type ListTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof listTeams>>>
export type ListTeamsQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListTeams<TData = Awaited<ReturnType<typeof listTeams>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeams>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createTeam = (
    team: MaybeRef<NonReadonly<Team>>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      team = unref(team);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: team, signal
    },
      options);
    }
  


export const getCreateTeamMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeam>>, TError,{data: BodyType<NonReadonly<Team>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTeam>>, TError,{data: BodyType<NonReadonly<Team>>}, TContext> => {

const mutationKey = ['createTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTeam>>, {data: BodyType<NonReadonly<Team>>}> = (props) => {
          const {data} = props ?? {};

          return  createTeam(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTeamMutationResult = NonNullable<Awaited<ReturnType<typeof createTeam>>>
    export type CreateTeamMutationBody = BodyType<NonReadonly<Team>>
    export type CreateTeamMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateTeam = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeam>>, TError,{data: BodyType<NonReadonly<Team>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createTeam>>,
        TError,
        {data: BodyType<NonReadonly<Team>>},
        TContext
      > => {

      const mutationOptions = getCreateTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getTeam = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTeamQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','teams',id
    ] as const;
    }

    
export const getGetTeamQueryOptions = <TData = Awaited<ReturnType<typeof getTeam>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetTeamQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeam>>> = ({ signal }) => getTeam(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeam>>, TError, TData> 
}

export type GetTeamQueryResult = NonNullable<Awaited<ReturnType<typeof getTeam>>>
export type GetTeamQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>



export function useGetTeam<TData = Awaited<ReturnType<typeof getTeam>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeamQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceTeam = (
    id: MaybeRef<number>,
    team: MaybeRef<NonReadonly<Team>>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
team = unref(team);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: team
    },
      options);
    }
  


export const getReplaceTeamMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceTeam>>, TError,{id: number;data: BodyType<NonReadonly<Team>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceTeam>>, TError,{id: number;data: BodyType<NonReadonly<Team>>}, TContext> => {

const mutationKey = ['replaceTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceTeam>>, {id: number;data: BodyType<NonReadonly<Team>>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceTeam(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceTeamMutationResult = NonNullable<Awaited<ReturnType<typeof replaceTeam>>>
    export type ReplaceTeamMutationBody = BodyType<NonReadonly<Team>>
    export type ReplaceTeamMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useReplaceTeam = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceTeam>>, TError,{id: number;data: BodyType<NonReadonly<Team>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceTeam>>,
        TError,
        {id: number;data: BodyType<NonReadonly<Team>>},
        TContext
      > => {

      const mutationOptions = getReplaceTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateTeam = (
    id: MaybeRef<number>,
    patchedTeam: MaybeRef<NonReadonly<PatchedTeam>>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
patchedTeam = unref(patchedTeam);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedTeam
    },
      options);
    }
  


export const getUpdateTeamMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeam>>, TError,{id: number;data: BodyType<NonReadonly<PatchedTeam>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTeam>>, TError,{id: number;data: BodyType<NonReadonly<PatchedTeam>>}, TContext> => {

const mutationKey = ['updateTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTeam>>, {id: number;data: BodyType<NonReadonly<PatchedTeam>>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTeam(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTeamMutationResult = NonNullable<Awaited<ReturnType<typeof updateTeam>>>
    export type UpdateTeamMutationBody = BodyType<NonReadonly<PatchedTeam>>
    export type UpdateTeamMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateTeam = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeam>>, TError,{id: number;data: BodyType<NonReadonly<PatchedTeam>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateTeam>>,
        TError,
        {id: number;data: BodyType<NonReadonly<PatchedTeam>>},
        TContext
      > => {

      const mutationOptions = getUpdateTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteTeam = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/teams/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTeamMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeam>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTeam>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTeam>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTeam(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTeamMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTeam>>>
    
    export type DeleteTeamMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteTeam = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeam>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteTeam>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateTeamBanner2 = (
    id: MaybeRef<number>,
    updateTeamBanner2Body: MaybeRef<UpdateTeamBanner2Body>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
updateTeamBanner2Body = unref(updateTeamBanner2Body);
      const formData = new FormData();
if(updateTeamBanner2Body.banner !== undefined) {
 formData.append(`banner`, updateTeamBanner2Body.banner)
 }

      return customInstance<TeamBanner>(
      {url: `http://localhost:8000/api/teams/${id}/banner/`, method: 'PUT',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getUpdateTeamBanner2MutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamBanner2>>, TError,{id: number;data: BodyType<UpdateTeamBanner2Body>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTeamBanner2>>, TError,{id: number;data: BodyType<UpdateTeamBanner2Body>}, TContext> => {

const mutationKey = ['updateTeamBanner2'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTeamBanner2>>, {id: number;data: BodyType<UpdateTeamBanner2Body>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTeamBanner2(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTeamBanner2MutationResult = NonNullable<Awaited<ReturnType<typeof updateTeamBanner2>>>
    export type UpdateTeamBanner2MutationBody = BodyType<UpdateTeamBanner2Body>
    export type UpdateTeamBanner2MutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateTeamBanner2 = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamBanner2>>, TError,{id: number;data: BodyType<UpdateTeamBanner2Body>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateTeamBanner2>>,
        TError,
        {id: number;data: BodyType<UpdateTeamBanner2Body>},
        TContext
      > => {

      const mutationOptions = getUpdateTeamBanner2MutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateTeamBanner = (
    id: MaybeRef<number>,
    updateTeamBannerBody: MaybeRef<UpdateTeamBannerBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
updateTeamBannerBody = unref(updateTeamBannerBody);
      const formData = new FormData();
if(updateTeamBannerBody.banner !== undefined) {
 formData.append(`banner`, updateTeamBannerBody.banner)
 }

      return customInstance<TeamBanner>(
      {url: `http://localhost:8000/api/teams/${id}/banner/`, method: 'PATCH',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getUpdateTeamBannerMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamBanner>>, TError,{id: number;data: BodyType<UpdateTeamBannerBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTeamBanner>>, TError,{id: number;data: BodyType<UpdateTeamBannerBody>}, TContext> => {

const mutationKey = ['updateTeamBanner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTeamBanner>>, {id: number;data: BodyType<UpdateTeamBannerBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTeamBanner(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTeamBannerMutationResult = NonNullable<Awaited<ReturnType<typeof updateTeamBanner>>>
    export type UpdateTeamBannerMutationBody = BodyType<UpdateTeamBannerBody>
    export type UpdateTeamBannerMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateTeamBanner = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTeamBanner>>, TError,{id: number;data: BodyType<UpdateTeamBannerBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateTeamBanner>>,
        TError,
        {id: number;data: BodyType<UpdateTeamBannerBody>},
        TContext
      > => {

      const mutationOptions = getUpdateTeamBannerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteTeamBanner = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<TeamBanner>(
      {url: `http://localhost:8000/api/teams/${id}/banner/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTeamBannerMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeamBanner>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTeamBanner>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteTeamBanner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTeamBanner>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTeamBanner(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTeamBannerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTeamBanner>>>
    
    export type DeleteTeamBannerMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteTeamBanner = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTeamBanner>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteTeamBanner>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteTeamBannerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listTeamInvitationsByTeam = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<TeamInvitation[]>(
      {url: `http://localhost:8000/api/teams/${id}/invitations/`, method: 'GET', signal
    },
      options);
    }
  



export const getListTeamInvitationsByTeamQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','teams',id,'invitations'
    ] as const;
    }

    
export const getListTeamInvitationsByTeamQueryOptions = <TData = Awaited<ReturnType<typeof listTeamInvitationsByTeam>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamInvitationsByTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListTeamInvitationsByTeamQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeamInvitationsByTeam>>> = ({ signal }) => listTeamInvitationsByTeam(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeamInvitationsByTeam>>, TError, TData> 
}

export type ListTeamInvitationsByTeamQueryResult = NonNullable<Awaited<ReturnType<typeof listTeamInvitationsByTeam>>>
export type ListTeamInvitationsByTeamQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>



export function useListTeamInvitationsByTeam<TData = Awaited<ReturnType<typeof listTeamInvitationsByTeam>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamInvitationsByTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamInvitationsByTeamQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createTeamJoinRequest = (
    id: MaybeRef<number>,
    detailResponse: MaybeRef<DetailResponse>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
detailResponse = unref(detailResponse);
      
      return customInstance<DetailResponse | DetailResponse>(
      {url: `http://localhost:8000/api/teams/${id}/join-requests/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: detailResponse, signal
    },
      options);
    }
  


export const getCreateTeamJoinRequestMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeamJoinRequest>>, TError,{id: number;data: BodyType<DetailResponse>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTeamJoinRequest>>, TError,{id: number;data: BodyType<DetailResponse>}, TContext> => {

const mutationKey = ['createTeamJoinRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTeamJoinRequest>>, {id: number;data: BodyType<DetailResponse>}> = (props) => {
          const {id,data} = props ?? {};

          return  createTeamJoinRequest(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTeamJoinRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createTeamJoinRequest>>>
    export type CreateTeamJoinRequestMutationBody = BodyType<DetailResponse>
    export type CreateTeamJoinRequestMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useCreateTeamJoinRequest = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTeamJoinRequest>>, TError,{id: number;data: BodyType<DetailResponse>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createTeamJoinRequest>>,
        TError,
        {id: number;data: BodyType<DetailResponse>},
        TContext
      > => {

      const mutationOptions = getCreateTeamJoinRequestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listTeamJoinRequestsByTeam = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<TeamJoinRequest[]>(
      {url: `http://localhost:8000/api/teams/${id}/join-requests-list/`, method: 'GET', signal
    },
      options);
    }
  



export const getListTeamJoinRequestsByTeamQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','teams',id,'join-requests-list'
    ] as const;
    }

    
export const getListTeamJoinRequestsByTeamQueryOptions = <TData = Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListTeamJoinRequestsByTeamQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>> = ({ signal }) => listTeamJoinRequestsByTeam(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>, TError, TData> 
}

export type ListTeamJoinRequestsByTeamQueryResult = NonNullable<Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>>
export type ListTeamJoinRequestsByTeamQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>



export function useListTeamJoinRequestsByTeam<TData = Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamJoinRequestsByTeam>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamJoinRequestsByTeamQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const acceptTeamJoinRequest = (
    id: MaybeRef<number>,
    requestId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
requestId = unref(requestId);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/${id}/join-requests/${requestId}/accept/`, method: 'POST', signal
    },
      options);
    }
  


export const getAcceptTeamJoinRequestMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptTeamJoinRequest>>, TError,{id: number;requestId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof acceptTeamJoinRequest>>, TError,{id: number;requestId: number}, TContext> => {

const mutationKey = ['acceptTeamJoinRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptTeamJoinRequest>>, {id: number;requestId: number}> = (props) => {
          const {id,requestId} = props ?? {};

          return  acceptTeamJoinRequest(id,requestId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcceptTeamJoinRequestMutationResult = NonNullable<Awaited<ReturnType<typeof acceptTeamJoinRequest>>>
    
    export type AcceptTeamJoinRequestMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useAcceptTeamJoinRequest = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptTeamJoinRequest>>, TError,{id: number;requestId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof acceptTeamJoinRequest>>,
        TError,
        {id: number;requestId: number},
        TContext
      > => {

      const mutationOptions = getAcceptTeamJoinRequestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const declineTeamJoinRequest = (
    id: MaybeRef<number>,
    requestId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
requestId = unref(requestId);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/${id}/join-requests/${requestId}/decline/`, method: 'POST', signal
    },
      options);
    }
  


export const getDeclineTeamJoinRequestMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof declineTeamJoinRequest>>, TError,{id: number;requestId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof declineTeamJoinRequest>>, TError,{id: number;requestId: number}, TContext> => {

const mutationKey = ['declineTeamJoinRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof declineTeamJoinRequest>>, {id: number;requestId: number}> = (props) => {
          const {id,requestId} = props ?? {};

          return  declineTeamJoinRequest(id,requestId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeclineTeamJoinRequestMutationResult = NonNullable<Awaited<ReturnType<typeof declineTeamJoinRequest>>>
    
    export type DeclineTeamJoinRequestMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeclineTeamJoinRequest = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof declineTeamJoinRequest>>, TError,{id: number;requestId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof declineTeamJoinRequest>>,
        TError,
        {id: number;requestId: number},
        TContext
      > => {

      const mutationOptions = getDeclineTeamJoinRequestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const leaveTeam = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<DetailResponse>(
      {url: `http://localhost:8000/api/teams/${id}/leave/`, method: 'POST', signal
    },
      options);
    }
  


export const getLeaveTeamMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveTeam>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof leaveTeam>>, TError,{id: number}, TContext> => {

const mutationKey = ['leaveTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof leaveTeam>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  leaveTeam(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LeaveTeamMutationResult = NonNullable<Awaited<ReturnType<typeof leaveTeam>>>
    
    export type LeaveTeamMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useLeaveTeam = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof leaveTeam>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof leaveTeam>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getLeaveTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inviteMemberToTeam = (
    id: MaybeRef<number>,
    inviteMemberRequest: MaybeRef<InviteMemberRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
inviteMemberRequest = unref(inviteMemberRequest);
      
      return customInstance<Team | Team>(
      {url: `http://localhost:8000/api/teams/${id}/members/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inviteMemberRequest, signal
    },
      options);
    }
  


export const getInviteMemberToTeamMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteMemberToTeam>>, TError,{id: number;data: BodyType<InviteMemberRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof inviteMemberToTeam>>, TError,{id: number;data: BodyType<InviteMemberRequest>}, TContext> => {

const mutationKey = ['inviteMemberToTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inviteMemberToTeam>>, {id: number;data: BodyType<InviteMemberRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  inviteMemberToTeam(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InviteMemberToTeamMutationResult = NonNullable<Awaited<ReturnType<typeof inviteMemberToTeam>>>
    export type InviteMemberToTeamMutationBody = BodyType<InviteMemberRequest>
    export type InviteMemberToTeamMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useInviteMemberToTeam = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inviteMemberToTeam>>, TError,{id: number;data: BodyType<InviteMemberRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof inviteMemberToTeam>>,
        TError,
        {id: number;data: BodyType<InviteMemberRequest>},
        TContext
      > => {

      const mutationOptions = getInviteMemberToTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const removeMemberFromTeam = (
    id: MaybeRef<number>,
    userId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
userId = unref(userId);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/teams/${id}/members/${userId}/`, method: 'DELETE'
    },
      options);
    }
  


export const getRemoveMemberFromTeamMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMemberFromTeam>>, TError,{id: number;userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeMemberFromTeam>>, TError,{id: number;userId: number}, TContext> => {

const mutationKey = ['removeMemberFromTeam'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeMemberFromTeam>>, {id: number;userId: number}> = (props) => {
          const {id,userId} = props ?? {};

          return  removeMemberFromTeam(id,userId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveMemberFromTeamMutationResult = NonNullable<Awaited<ReturnType<typeof removeMemberFromTeam>>>
    
    export type RemoveMemberFromTeamMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useRemoveMemberFromTeam = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeMemberFromTeam>>, TError,{id: number;userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof removeMemberFromTeam>>,
        TError,
        {id: number;userId: number},
        TContext
      > => {

      const mutationOptions = getRemoveMemberFromTeamMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listTeamInvitations = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TeamInvitationInbox[]>(
      {url: `http://localhost:8000/api/teams/invitations/`, method: 'GET', signal
    },
      options);
    }
  



export const getListTeamInvitationsQueryKey = () => {
    return [
    'http:','localhost:8000','api','teams','invitations'
    ] as const;
    }

    
export const getListTeamInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof listTeamInvitations>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamInvitations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListTeamInvitationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeamInvitations>>> = ({ signal }) => listTeamInvitations(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeamInvitations>>, TError, TData> 
}

export type ListTeamInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof listTeamInvitations>>>
export type ListTeamInvitationsQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListTeamInvitations<TData = Awaited<ReturnType<typeof listTeamInvitations>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTeamInvitations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTeamInvitationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const acceptTeamInvitation = (
    invitationId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      invitationId = unref(invitationId);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/invitations/${invitationId}/accept/`, method: 'POST', signal
    },
      options);
    }
  


export const getAcceptTeamInvitationMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptTeamInvitation>>, TError,{invitationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof acceptTeamInvitation>>, TError,{invitationId: number}, TContext> => {

const mutationKey = ['acceptTeamInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptTeamInvitation>>, {invitationId: number}> = (props) => {
          const {invitationId} = props ?? {};

          return  acceptTeamInvitation(invitationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AcceptTeamInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof acceptTeamInvitation>>>
    
    export type AcceptTeamInvitationMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useAcceptTeamInvitation = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptTeamInvitation>>, TError,{invitationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof acceptTeamInvitation>>,
        TError,
        {invitationId: number},
        TContext
      > => {

      const mutationOptions = getAcceptTeamInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const declineTeamInvitation = (
    invitationId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      invitationId = unref(invitationId);
      
      return customInstance<Team>(
      {url: `http://localhost:8000/api/teams/invitations/${invitationId}/decline/`, method: 'POST', signal
    },
      options);
    }
  


export const getDeclineTeamInvitationMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof declineTeamInvitation>>, TError,{invitationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof declineTeamInvitation>>, TError,{invitationId: number}, TContext> => {

const mutationKey = ['declineTeamInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof declineTeamInvitation>>, {invitationId: number}> = (props) => {
          const {invitationId} = props ?? {};

          return  declineTeamInvitation(invitationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeclineTeamInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof declineTeamInvitation>>>
    
    export type DeclineTeamInvitationMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useDeclineTeamInvitation = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof declineTeamInvitation>>, TError,{invitationId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof declineTeamInvitation>>,
        TError,
        {invitationId: number},
        TContext
      > => {

      const mutationOptions = getDeclineTeamInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    