/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  DeletedCountResponse,
  DetailResponse,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponseValidationError,
  GlobalConfigUpdateRequest,
  ListNotificationsParams,
  MarkedCountResponse,
  NotificationConfigUpdateRequest,
  NotificationSettingsResponse,
  PaginatedNotificationList,
  UnreadCountResponse
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List current user's notifications, newest first.
 */
export const listNotifications = (
    params?: MaybeRef<ListNotificationsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedNotificationList>(
      {url: `http://localhost:8000/api/notifications/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListNotificationsQueryKey = (params?: MaybeRef<ListNotificationsParams>,) => {
    return [
    'http:','localhost:8000','api','notifications', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListNotificationsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListNotificationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotifications>>> = ({ signal }) => listNotifications(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData> 
}

export type ListNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof listNotifications>>>
export type ListNotificationsQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListNotifications<TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListNotificationsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListNotificationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const deleteNotification = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/notifications/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteNotificationMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteNotification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNotification>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteNotification(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNotification>>>
    
    export type DeleteNotificationMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useDeleteNotification = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteNotification>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteNotificationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const markNotificationRead = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<DetailResponse>(
      {url: `http://localhost:8000/api/notifications/${id}/read/`, method: 'POST', signal
    },
      options);
    }
  


export const getMarkNotificationReadMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError,{id: number}, TContext> => {

const mutationKey = ['markNotificationRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markNotificationRead>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  markNotificationRead(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarkNotificationReadMutationResult = NonNullable<Awaited<ReturnType<typeof markNotificationRead>>>
    
    export type MarkNotificationReadMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useMarkNotificationRead = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof markNotificationRead>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getMarkNotificationReadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAllNotifications = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeletedCountResponse>(
      {url: `http://localhost:8000/api/notifications/delete-all/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAllNotificationsMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllNotifications>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAllNotifications>>, TError,void, TContext> => {

const mutationKey = ['deleteAllNotifications'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAllNotifications>>, void> = () => {
          

          return  deleteAllNotifications(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAllNotificationsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAllNotifications>>>
    
    export type DeleteAllNotificationsMutationError = ErrorType<ErrorResponseNotAuthenticated>

    export const useDeleteAllNotifications = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAllNotifications>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteAllNotifications>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteAllNotificationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const markAllNotificationsRead = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MarkedCountResponse>(
      {url: `http://localhost:8000/api/notifications/read-all/`, method: 'POST', signal
    },
      options);
    }
  


export const getMarkAllNotificationsReadMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError,void, TContext> => {

const mutationKey = ['markAllNotificationsRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markAllNotificationsRead>>, void> = () => {
          

          return  markAllNotificationsRead(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MarkAllNotificationsReadMutationResult = NonNullable<Awaited<ReturnType<typeof markAllNotificationsRead>>>
    
    export type MarkAllNotificationsReadMutationError = ErrorType<ErrorResponseNotAuthenticated>

    export const useMarkAllNotificationsRead = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsRead>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof markAllNotificationsRead>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getMarkAllNotificationsReadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getNotificationSettings = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<NotificationSettingsResponse>(
      {url: `http://localhost:8000/api/notifications/settings/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetNotificationSettingsQueryKey = () => {
    return [
    'http:','localhost:8000','api','notifications','settings'
    ] as const;
    }

    
export const getGetNotificationSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetNotificationSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationSettings>>> = ({ signal }) => getNotificationSettings(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData> 
}

export type GetNotificationSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationSettings>>>
export type GetNotificationSettingsQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useGetNotificationSettings<TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotificationSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const updateNotificationConfig = (
    notificationConfigUpdateRequest: MaybeRef<NotificationConfigUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      notificationConfigUpdateRequest = unref(notificationConfigUpdateRequest);
      
      return customInstance<DetailResponse>(
      {url: `http://localhost:8000/api/notifications/settings/config/update/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notificationConfigUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateNotificationConfigMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationConfig>>, TError,{data: BodyType<NotificationConfigUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateNotificationConfig>>, TError,{data: BodyType<NotificationConfigUpdateRequest>}, TContext> => {

const mutationKey = ['updateNotificationConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNotificationConfig>>, {data: BodyType<NotificationConfigUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  updateNotificationConfig(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNotificationConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotificationConfig>>>
    export type UpdateNotificationConfigMutationBody = BodyType<NotificationConfigUpdateRequest>
    export type UpdateNotificationConfigMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useUpdateNotificationConfig = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationConfig>>, TError,{data: BodyType<NotificationConfigUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateNotificationConfig>>,
        TError,
        {data: BodyType<NotificationConfigUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateNotificationConfigMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateGlobalNotificationConfig = (
    globalConfigUpdateRequest: MaybeRef<GlobalConfigUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      globalConfigUpdateRequest = unref(globalConfigUpdateRequest);
      
      return customInstance<DetailResponse>(
      {url: `http://localhost:8000/api/notifications/settings/global/update/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: globalConfigUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateGlobalNotificationConfigMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGlobalNotificationConfig>>, TError,{data: BodyType<GlobalConfigUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGlobalNotificationConfig>>, TError,{data: BodyType<GlobalConfigUpdateRequest>}, TContext> => {

const mutationKey = ['updateGlobalNotificationConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGlobalNotificationConfig>>, {data: BodyType<GlobalConfigUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  updateGlobalNotificationConfig(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGlobalNotificationConfigMutationResult = NonNullable<Awaited<ReturnType<typeof updateGlobalNotificationConfig>>>
    export type UpdateGlobalNotificationConfigMutationBody = BodyType<GlobalConfigUpdateRequest>
    export type UpdateGlobalNotificationConfigMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useUpdateGlobalNotificationConfig = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGlobalNotificationConfig>>, TError,{data: BodyType<GlobalConfigUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateGlobalNotificationConfig>>,
        TError,
        {data: BodyType<GlobalConfigUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateGlobalNotificationConfigMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getUnreadNotificationCount = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UnreadCountResponse>(
      {url: `http://localhost:8000/api/notifications/unread-count/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUnreadNotificationCountQueryKey = () => {
    return [
    'http:','localhost:8000','api','notifications','unread-count'
    ] as const;
    }

    
export const getGetUnreadNotificationCountQueryOptions = <TData = Awaited<ReturnType<typeof getUnreadNotificationCount>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadNotificationCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetUnreadNotificationCountQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnreadNotificationCount>>> = ({ signal }) => getUnreadNotificationCount(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnreadNotificationCount>>, TError, TData> 
}

export type GetUnreadNotificationCountQueryResult = NonNullable<Awaited<ReturnType<typeof getUnreadNotificationCount>>>
export type GetUnreadNotificationCountQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useGetUnreadNotificationCount<TData = Awaited<ReturnType<typeof getUnreadNotificationCount>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadNotificationCount>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUnreadNotificationCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




