# Generated by Django 5.2.4 on 2026-05-13 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_asset_url',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='UserDigitalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'digital'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='shop_inventory_user_product_unique')],
            },
        ),
    ]
