# Generated by Django 5.2.4 on 2026-05-13 19:16

from django.db import migrations


def create_avatar_frames(apps, schema_editor):
    AvatarFrame = apps.get_model('shop', 'AvatarFrame')

    # Create AvatarFrame objects for existing SVG files
    frames_data = [
        {'name': 'Aurora Pulse', 'filename': 'aurora-pulse.svg'},
        {'name': 'Fire Tongues', 'filename': 'fire-tongues.svg'},
    ]

    for frame_data in frames_data:
        AvatarFrame.objects.get_or_create(
            name=frame_data['name'],
            defaults={
                'svg_file': f'avatar-frames/{frame_data["filename"]}',
                'is_active': True,
            }
        )


def migrate_products_to_avatar_frames(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    AvatarFrame = apps.get_model('shop', 'AvatarFrame')

    # Map old URLs to AvatarFrame objects
    url_to_frame = {
        '/avatar-frames/aurora-pulse.svg': 'Aurora Pulse',
        '/avatar-frames/fire-tongues.svg': 'Fire Tongues',
    }

    for product in Product.objects.filter(digital_asset_url__in=url_to_frame.keys()):
        frame_name = url_to_frame[product.digital_asset_url]
        try:
            frame = AvatarFrame.objects.get(name=frame_name)
            product.avatar_frame = frame
            product.save(update_fields=['avatar_frame'])
        except AvatarFrame.DoesNotExist:
            pass  # Skip if frame doesn't exist


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_avatarframe_product_avatar_frame'),
    ]

    operations = [
        migrations.RunPython(create_avatar_frames, migrations.RunPython.noop),
        migrations.RunPython(migrate_products_to_avatar_frames, migrations.RunPython.noop),
    ]
