# Generated by Django 5.2.4 on 2026-05-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_migrate_to_avatar_frames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDigitalInventory',
        ),
    ]
