# Generated by Django 5.2.4 on 2026-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_remove_event_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteamregistration',
            name='disqualification_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
