# Generated by Django 5.2.4 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournamentteamregistration_disqualification_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteamregistration',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]

