# Generated by Django 6.0.5 on 2026-05-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_tournamentteamregistration_is_disqualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='round',
            name='materials',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
