/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
/**
 * * `disqualify` - disqualify
* `reactivate` - reactivate
 */
export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionEnum = {
  disqualify: 'disqualify',
  reactivate: 'reactivate',
} as const;

export interface ActivationResponse {
  status: string;
  message: string;
}

export interface ActiveCounts {
  jury: number;
  organizer: number;
  admin: number;
}

export interface ActiveTournament {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  status?: StatusD67Enum;
  start_date: string;
}

export interface AdminModifyPointsResponse {
  user: UserLookup;
  balance: UserPointsBalance;
  transaction: PointsTransaction;
}

export interface AdminPointsBalanceModifyRequest {
  operation: OperationEnum;
  amount?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  reason: string;
}

export interface AdminStats {
  total_users: number;
  total_teams: number;
  total_tournaments: number;
  new_registrations_last_7_days: number;
  new_registrations_last_30_days: number;
  active_tournaments: number;
  users_by_role: RoleBreakdownItem[];
  total_evaluation_records: number;
}

/**
 * @nullable
 */
export type ArchiveStandingJuryBreakdown = unknown | null;

/**
 * @nullable
 */
export type ArchiveStandingRoundsBreakdown = unknown | null;

export interface ArchiveStanding {
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  rank: number;
  readonly team: TeamSummary;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  total_score: string;
  /** @pattern ^-?\d{0,4}(?:\.\d{0,2})?$ */
  average_score: string;
  criteria_breakdown: unknown;
  /** @nullable */
  jury_breakdown?: ArchiveStandingJuryBreakdown;
  /** @nullable */
  rounds_breakdown?: ArchiveStandingRoundsBreakdown;
  readonly snapshot_at: string;
}

export interface AssignJuryResponse {
  status: string;
  created_assignments: number;
}

export interface AvailableJury {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 255 */
  full_name?: string;
}

export interface AvatarFrame {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  svg_file: string;
  is_active?: boolean;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface AvatarFrameRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  svg_file: Blob;
  is_active?: boolean;
}

export interface CalendarExportError {
  type: TypeBd0Enum;
  id: number;
  error: string;
}

export interface Category {
  readonly id: number;
  /** @maxLength 120 */
  name: string;
}

export interface CategoryRequest {
  /**
   * @minLength 1
   * @maxLength 120
   */
  name: string;
}

export interface Certificate {
  readonly id: number;
  readonly unique_code: string;
  /** @nullable */
  user?: number | null;
  readonly full_name: string;
  /** @nullable */
  team?: number | null;
  readonly team_name: string;
  /** @nullable */
  tournament?: number | null;
  readonly tournament_name: string;
  /** @maxLength 100 */
  placement: string;
  /** @maxLength 100 */
  certificate_number?: string;
  /** @nullable */
  template?: number | null;
  readonly template_name: string;
  readonly certificate_url: string;
  readonly created_at: string;
}

export interface CertificateRequest {
  /** @nullable */
  user?: number | null;
  /** @nullable */
  team?: number | null;
  /** @nullable */
  tournament?: number | null;
  /**
   * @minLength 1
   * @maxLength 100
   */
  placement: string;
  /** @maxLength 100 */
  certificate_number?: string;
  /** @nullable */
  template?: number | null;
}

export interface CertificateTemplate {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  image: string;
  is_default?: boolean;
  /** @nullable */
  readonly image_url: string | null;
  readonly created_at: string;
}

export interface CertificateTemplateRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  image: Blob;
  is_default?: boolean;
}

export interface ChangePasswordRequest {
  /** @minLength 1 */
  current_password: string;
  /** @minLength 1 */
  new_password: string;
  /** @minLength 1 */
  confirm_password: string;
}

export interface Criterion {
  id: string;
  name: string;
  description: string;
  max_score: number;
}

export interface CriterionRequest {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  max_score: number;
}

export interface CurrentTask {
  readonly id: number;
  readonly tournament_id: number;
  readonly tournament_name: string;
  /** @maxLength 255 */
  name?: string;
  readonly task: string;
  readonly deadline: string;
  must_have_requirements?: unknown;
  tech_requirements?: unknown;
}

export interface DeletedCountResponse {
  deleted: number;
}

export interface DetailResponse {
  detail: string;
}

export interface DigitalInventoryItem {
  readonly id: number;
  readonly product: Product;
  readonly is_equipped: boolean;
  readonly acquired_at: string;
  readonly updated_at: string;
}

export interface DisqualificationResponse {
  id: number;
  team_id: number;
  team_name: string;
  tournament_id: number;
  is_active: boolean;
  action: string;
}

export interface EligibleTeam {
  id: number;
  name: string;
  members_count: number;
}

export interface EquipDigitalItemRequest {
  /** @minimum 1 */
  inventory_id: number;
}

export interface ErrorResponseNotAuthenticated {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error summary. */
  message: string;
  /**
   * Always null for non-validation errors.
   * @nullable
   */
  details?: string | null;
}

export interface ErrorResponseNotFound {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error summary. */
  message: string;
  /**
   * Always null for non-validation errors.
   * @nullable
   */
  details?: string | null;
}

export interface ErrorResponsePermissionDenied {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error summary. */
  message: string;
  /**
   * Always null for non-validation errors.
   * @nullable
   */
  details?: string | null;
}

export interface ErrorResponseServiceUnavailable {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error summary. */
  message: string;
  /**
   * Always null for non-validation errors.
   * @nullable
   */
  details?: string | null;
}

/**
 * Field-level validation errors. Keys are field names, values are lists of messages.
 */
export type ErrorResponseValidationErrorDetails = {[key: string]: string[]};

export interface ErrorResponseValidationError {
  /** Machine-readable error code. */
  code: string;
  /** Human-readable error summary. */
  message: string;
  /** Field-level validation errors. Keys are field names, values are lists of messages. */
  details: ErrorResponseValidationErrorDetails;
}

/**
 * * `score` - Score
 */
export type EvaluationCriteriaEnum = typeof EvaluationCriteriaEnum[keyof typeof EvaluationCriteriaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluationCriteriaEnum = {
  score: 'score',
} as const;

export interface EvaluationRoundShort {
  readonly id: number;
  /** @maxLength 255 */
  name?: string;
  start_date: string;
  end_date: string;
  status?: StatusE43Enum;
  criteria: unknown;
  tournament: number;
}

export interface EvaluationSubmissionEvaluation {
  readonly id: number;
  assignment: number;
  scores: ScoreItem[];
  readonly total_score: number;
  /** @pattern ^-?\d{0,3}(?:\.\d{0,2})?$ */
  readonly final_score: string;
  comment?: string;
  readonly created_at: string;
}

export interface EvaluationSubmissionEvaluationRequest {
  tournament_id: number;
  assignment: number;
  scores: ScoreItemRequest[];
  comment?: string;
}

export interface Event {
  readonly id: number;
  tournament: number;
  type: EventTypeEnum;
  /** @maxLength 255 */
  title: string;
  description?: string;
  /** @maxLength 200 */
  link?: string;
  start_datetime: string;
  /** @nullable */
  icon?: number | null;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface EventRequest {
  tournament: number;
  type: EventTypeEnum;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  description?: string;
  /** @maxLength 200 */
  link?: string;
  start_datetime: string;
  /** @nullable */
  icon?: number | null;
}

export interface EventType {
  key: string;
  title: string;
}

/**
 * * `meet` - Meet
* `event` - Event
 */
export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventTypeEnum = {
  meet: 'meet',
  event: 'event',
} as const;

export interface ExportToGoogleCalendarRequestRequest {
  event_ids?: number[];
  round_ids?: number[];
}

export interface ExportToGoogleCalendarResponse {
  created: ExportedCalendarItem[];
  errors: CalendarExportError[];
}

export interface ExportedCalendarItem {
  type: TypeBd0Enum;
  id: number;
  google_event_id?: string;
  google_event_ids?: string[];
  html_link?: string;
}

export interface GlobalConfig {
  emails_disabled_globally: boolean;
}

export interface GlobalConfigUpdateRequest {
  emails_disabled_globally: boolean;
}

export interface GoogleAuthRequest {
  /** @minLength 1 */
  id_token: string;
}

export interface GoogleAuthResponse {
  access: string;
  refresh: string;
  user: User;
  onboarding_required: boolean;
}

export interface GoogleCalendarCallbackRequestRequest {
  /** @minLength 1 */
  code: string;
}

export interface GoogleCalendarConnectResponse {
  auth_url: string;
}

export interface GoogleCalendarStatus {
  connected: boolean;
}

export interface Icon {
  readonly id: number;
  /** @maxLength 255 */
  name?: string;
  /** @maxLength 500 */
  path: string;
}

export interface InviteMemberRequestRequest {
  user_id: number;
}

export interface JuryAssignment {
  readonly id: number;
  submission: number;
  readonly submission_details: Submission;
  readonly round_details: EvaluationRoundShort;
  readonly evaluation: EvaluationSubmissionEvaluation;
  readonly is_evaluated: boolean;
  readonly created_at: string;
}

export interface JuryAssignmentItemRequest {
  submission: number;
  jury: number[];
}

export interface LoginRequestRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

export interface LoginResponse {
  access: string;
  refresh: string;
}

export interface MarkedCountResponse {
  marked: number;
}

export interface MessageResponse {
  message: string;
}

export interface MyCalendarResponse {
  events: Event[];
  rounds: Round[];
}

export type NewsArticleContent = {[key: string]: unknown};

export interface NewsArticle {
  readonly id: number;
  /** @maxLength 255 */
  title: string;
  content: NewsArticleContent;
  /** @nullable */
  readonly created_by: number | null;
  readonly created_by_name: string;
  readonly created_at: string;
  readonly updated_at: string;
}

export type NewsArticleRequestContent = {[key: string]: unknown};

export interface NewsArticleRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  content: NewsArticleRequestContent;
  send_notification?: boolean;
}

export interface Notification {
  readonly id: number;
  readonly event_type: string;
  readonly title: string;
  readonly message: string;
  readonly is_read: boolean;
  readonly created_at: string;
}

export interface NotificationConfig {
  event_type: string;
  is_system_enabled: boolean;
  is_email_enabled: boolean;
}

export interface NotificationConfigUpdateRequest {
  /** @minLength 1 */
  event_type: string;
  is_system_enabled?: boolean;
  is_email_enabled?: boolean;
}

export interface NotificationSettingsResponse {
  event_types: EventType[];
  configs: NotificationConfig[];
  global_config: GlobalConfig;
}

/**
 * * `add` - Add
* `subtract` - Subtract
* `set` - Set
* `reset` - Reset
 */
export type OperationEnum = typeof OperationEnum[keyof typeof OperationEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OperationEnum = {
  add: 'add',
  subtract: 'subtract',
  set: 'set',
  reset: 'reset',
} as const;

export interface Order {
  readonly id: number;
  readonly user: UserShort;
  readonly user_profile_url: string;
  readonly product: Product;
  readonly quantity: number;
  readonly total_cost: number;
  readonly status: Status7deEnum;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface OwnSubmission {
  readonly id: number;
  readonly team: TeamSummary;
  readonly round: RoundShort;
  /** @maxLength 200 */
  github_url: string;
  /** @maxLength 200 */
  demo_video_url?: string;
  demo_video_file?: string;
  /** @maxLength 200 */
  live_demo_url?: string;
  description?: string;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface PaginatedAvatarFrameList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: AvatarFrame[];
}

export interface PaginatedCategoryList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Category[];
}

export interface PaginatedCertificateList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Certificate[];
}

export interface PaginatedCertificateTemplateList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: CertificateTemplate[];
}

export interface PaginatedDigitalInventoryItemList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: DigitalInventoryItem[];
}

export interface PaginatedJuryAssignmentList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: JuryAssignment[];
}

export interface PaginatedNewsArticleList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: NewsArticle[];
}

export interface PaginatedNotificationList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Notification[];
}

export interface PaginatedOrderList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Order[];
}

export interface PaginatedPointsTransactionList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: PointsTransaction[];
}

export interface PaginatedProductList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Product[];
}

export interface PassingStatusItem {
  rank: number;
  team_id: number;
  team_name: string;
  total_score: number;
  average_score: number;
  passed: boolean;
  /** @nullable */
  is_active: boolean | null;
  /** @nullable */
  disqualification_reason: string | null;
  /** @nullable */
  registration_id: number | null;
}

export interface PasswordResetConfirmRequest {
  /** @minLength 1 */
  new_password: string;
  /** @minLength 1 */
  confirm_password: string;
}

export interface PasswordResetRequestRequest {
  /** @minLength 1 */
  email: string;
}

export interface PatchedAdminOrderStatusUpdateRequest {
  status?: Status7deEnum;
}

export interface PatchedAvatarFrameRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  svg_file?: Blob;
  is_active?: boolean;
}

export interface PatchedCategoryRequest {
  /**
   * @minLength 1
   * @maxLength 120
   */
  name?: string;
}

export interface PatchedCertificateRequest {
  /** @nullable */
  user?: number | null;
  /** @nullable */
  team?: number | null;
  /** @nullable */
  tournament?: number | null;
  /**
   * @minLength 1
   * @maxLength 100
   */
  placement?: string;
  /** @maxLength 100 */
  certificate_number?: string;
  /** @nullable */
  template?: number | null;
}

export interface PatchedCertificateTemplateRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  image?: Blob;
  is_default?: boolean;
}

export interface PatchedEvaluationSubmissionEvaluationRequest {
  tournament_id?: number;
  assignment?: number;
  scores?: ScoreItemRequest[];
  comment?: string;
}

export interface PatchedEventRequest {
  tournament?: number;
  type?: EventTypeEnum;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  description?: string;
  /** @maxLength 200 */
  link?: string;
  start_datetime?: string;
  /** @nullable */
  icon?: number | null;
}

export type PatchedNewsArticleRequestContent = {[key: string]: unknown};

export interface PatchedNewsArticleRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  content?: PatchedNewsArticleRequestContent;
  send_notification?: boolean;
}

export interface PatchedProductRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  description?: string;
  /**
   * Price in points
   * @minimum 0
   * @maximum 9223372036854776000
   */
  price?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  stock_quantity?: number;
  category_id?: number;
  product_type?: ProductTypeEnum;
  /** @nullable */
  avatar_frame_id?: number | null;
  avatar_frame_file?: Blob;
  digital_asset_url?: string;
  uploaded_images?: Blob[];
  is_active?: boolean;
}

export interface PatchedRoundRequest {
  tournament?: number;
  /** @maxLength 255 */
  name?: string;
  description?: unknown;
  tech_requirements?: unknown;
  must_have_requirements?: unknown;
  criteria?: CriterionRequest[];
  start_date?: string;
  end_date?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  passing_count?: number | null;
  evaluation_criteria?: EvaluationCriteriaEnum;
  materials?: unknown;
}

export interface PatchedSubmissionRequest {
  round?: number;
  /**
   * @minLength 1
   * @maxLength 200
   */
  github_url?: string;
  /** @maxLength 200 */
  demo_video_url?: string;
  demo_video_file?: Blob;
  /** @maxLength 200 */
  live_demo_url?: string;
  description?: string;
}

export interface PatchedTeamBannerRequest {
  /** @nullable */
  banner?: Blob | null;
}

export interface PatchedTeamRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email?: string;
  is_public?: boolean;
  /** @maxLength 255 */
  organization?: string;
  /** @maxLength 100 */
  contact_telegram?: string;
  /** @maxLength 100 */
  contact_discord?: string;
  member_ids?: number[];
}

export interface PatchedTournamentAdminRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /** @minLength 1 */
  description?: string;
  start_date?: string;
  end_date?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  max_teams?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  min_team_members?: number | null;
}

export interface PatchedTournamentBannerRequest {
  /** @nullable */
  banner?: Blob | null;
}

export interface PatchedTournamentTeamRegistrationDisqualificationRequest {
  action?: ActionEnum;
  disqualification_reason?: string;
}

export interface PatchedUserAvatarUpdateRequest {
  /** @nullable */
  avatar?: Blob | null;
}

export interface PatchedUserUpdateRequest {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @minLength 1
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username?: string;
  role?: RoleB96Enum;
  /** @maxLength 255 */
  full_name?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  city?: string;
  /** @minLength 1 */
  password?: string;
  redeem_code?: string;
}

export interface PlayerStats {
  total_tournaments: number;
  wins: number;
  losses: number;
  win_rate: number;
  average_evaluation_score: number;
  /** @nullable */
  current_team_name: string | null;
}

export interface PointsTransaction {
  id: number;
  user_id: number;
  /** @nullable */
  order_id?: number | null;
  amount: number;
  reason: string;
  created_at: string;
}

export interface Product {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  description?: string;
  /**
   * Price in points
   * @minimum 0
   * @maximum 9223372036854776000
   */
  price: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  stock_quantity?: number;
  readonly category: Category;
  product_type?: ProductTypeEnum;
  readonly avatar_frame: AvatarFrame;
  digital_asset_url?: string;
  readonly images: readonly ProductImage[];
  is_active?: boolean;
  readonly is_available: boolean;
  readonly created_at: string;
  readonly updated_at: string;
}

export interface ProductImage {
  readonly id: number;
  image: string;
  readonly created_at: string;
}

export interface ProductImageRequest {
  image: Blob;
}

export interface ProductRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: string;
  /**
   * Price in points
   * @minimum 0
   * @maximum 9223372036854776000
   */
  price: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  stock_quantity?: number;
  category_id: number;
  product_type?: ProductTypeEnum;
  /** @nullable */
  avatar_frame_id?: number | null;
  avatar_frame_file?: Blob;
  digital_asset_url?: string;
  uploaded_images?: Blob[];
  is_active?: boolean;
}

/**
 * * `physical` - Physical
* `digital` - Digital
 */
export type ProductTypeEnum = typeof ProductTypeEnum[keyof typeof ProductTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductTypeEnum = {
  physical: 'physical',
  digital: 'digital',
} as const;

export interface PurchaseRequest {
  /** @minimum 1 */
  product_id: number;
  /** @minimum 1 */
  quantity: number;
}

export interface RankingItem {
  team_id: number;
  team_name: string;
  total_score: number;
  average_score: number;
  rank: number;
}

export interface Register {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email: string;
  role?: RoleB96Enum;
  /** @maxLength 255 */
  full_name?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  city?: string;
}

export interface RegisterRequest {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @minLength 1
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /** @minLength 1 */
  password: string;
  role?: RoleB96Enum;
  redeem_code?: string;
  /** @maxLength 255 */
  full_name?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  city?: string;
}

export interface RoleActivationCode {
  readonly id: number;
  /** @maxLength 24 */
  code: string;
  role: RoleB96Enum;
  is_used?: boolean;
  readonly created_at: string;
  /** @nullable */
  used_at?: string | null;
  readonly created_by_username: string;
  readonly used_by_username: string;
}

export interface RoleActivationCodeGenerateRequest {
  role: RoleActivationCodeGenerateRoleEnum;
  /**
   * @minimum 1
   * @maximum 10
   */
  quantity?: number;
}

export interface RoleActivationCodeGenerateResponse {
  created: RoleActivationCode[];
  active_counts: ActiveCounts;
}

/**
 * * `jury` - jury
* `admin` - admin
* `organizer` - organizer
 */
export type RoleActivationCodeGenerateRoleEnum = typeof RoleActivationCodeGenerateRoleEnum[keyof typeof RoleActivationCodeGenerateRoleEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleActivationCodeGenerateRoleEnum = {
  jury: 'jury',
  admin: 'admin',
  organizer: 'organizer',
} as const;

export interface RoleActivationCodeListResponse {
  codes: RoleActivationCode[];
  active_counts: ActiveCounts;
}

/**
 * * `admin` - Admin
* `team` - Team Member
* `jury` - Jury
* `organizer` - Organizer
 */
export type RoleB96Enum = typeof RoleB96Enum[keyof typeof RoleB96Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleB96Enum = {
  admin: 'admin',
  team: 'team',
  jury: 'jury',
  organizer: 'organizer',
} as const;

export interface RoleBreakdownItem {
  role: string;
  count: number;
}

export interface Round {
  readonly id: number;
  tournament?: number;
  /** @maxLength 255 */
  name?: string;
  description?: unknown;
  tech_requirements?: unknown;
  must_have_requirements?: unknown;
  criteria: Criterion[];
  start_date: string;
  end_date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  passing_count?: number | null;
  evaluation_criteria?: EvaluationCriteriaEnum;
  materials?: unknown;
  readonly status: StatusE43Enum;
}

export interface RoundLeaderboardResponse {
  round_id: number;
  is_snapshot: boolean;
  rankings: RankingItem[];
}

export interface RoundPassingStatusResponse {
  round_id: number;
  round_name: string;
  /** @nullable */
  passing_count: number | null;
  total_teams: number;
  results: PassingStatusItem[];
}

export interface RoundRequest {
  tournament?: number;
  /** @maxLength 255 */
  name?: string;
  description?: unknown;
  tech_requirements?: unknown;
  must_have_requirements?: unknown;
  criteria: CriterionRequest[];
  start_date: string;
  end_date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  passing_count?: number | null;
  evaluation_criteria?: EvaluationCriteriaEnum;
  materials?: unknown;
}

export interface RoundShort {
  readonly id: number;
  /** @maxLength 255 */
  name?: string;
  start_date: string;
  end_date: string;
  status?: StatusE43Enum;
  criteria: Criterion[];
  tournament: number;
}

export interface RoundShortRequest {
  /** @maxLength 255 */
  name?: string;
  start_date: string;
  end_date: string;
  status?: StatusE43Enum;
  criteria: CriterionRequest[];
  tournament: number;
}

/**
 * @nullable
 */
export type RoundSummaryJuryBreakdown = unknown | null;

export interface RoundSummary {
  round_id: number;
  round_name: string;
  total_score: number;
  average_score: number;
  /** @nullable */
  jury_breakdown?: RoundSummaryJuryBreakdown;
}

export interface ScoreItem {
  criterion_id: string;
  criterion_name: string;
  score: number;
}

export interface ScoreItemRequest {
  /** @minLength 1 */
  criterion_id: string;
  /** @minLength 1 */
  criterion_name: string;
  score: number;
}

/**
 * * `pending` - Pending
* `confirmed` - Confirmed
* `shipped` - Shipped
* `completed` - Completed
* `cancelled` - Cancelled
 */
export type Status7deEnum = typeof Status7deEnum[keyof typeof Status7deEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status7deEnum = {
  pending: 'pending',
  confirmed: 'confirmed',
  shipped: 'shipped',
  completed: 'completed',
  cancelled: 'cancelled',
} as const;

/**
 * * `invited` - Invited
* `accepted` - Accepted
* `declined` - Declined
 */
export type StatusB9dEnum = typeof StatusB9dEnum[keyof typeof StatusB9dEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusB9dEnum = {
  invited: 'invited',
  accepted: 'accepted',
  declined: 'declined',
} as const;

/**
 * * `draft` - Draft
* `registration` - Registration
* `running` - Running
* `finished` - Finished
 */
export type StatusD67Enum = typeof StatusD67Enum[keyof typeof StatusD67Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusD67Enum = {
  draft: 'draft',
  registration: 'registration',
  running: 'running',
  finished: 'finished',
} as const;

/**
 * * `draft` - Draft
* `active` - Active
* `submission_closed` - SubmissionClosed
* `evaluated` - Evaluated
 */
export type StatusE43Enum = typeof StatusE43Enum[keyof typeof StatusE43Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusE43Enum = {
  draft: 'draft',
  active: 'active',
  submission_closed: 'submission_closed',
  evaluated: 'evaluated',
} as const;

export interface Submission {
  readonly id: number;
  readonly team: number;
  readonly team_details: TeamSummary;
  readonly round_details: RoundShort;
  /** @maxLength 200 */
  github_url: string;
  /** @maxLength 200 */
  demo_video_url?: string;
  demo_video_file?: string;
  /** @maxLength 200 */
  live_demo_url?: string;
  description?: string;
  readonly assignments: readonly SubmissionAssignment[];
  readonly created_at: string;
  readonly updated_at: string;
}

export interface SubmissionAssignment {
  readonly id: number;
  readonly jury: SubmissionAssignmentJury;
  readonly evaluation: SubmissionEvaluation;
  readonly created_at: string;
}

export interface SubmissionAssignmentJury {
  id: number;
  username: string;
  full_name: string;
  role: string;
}

export interface SubmissionAssignmentJuryRequest {
  id: number;
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  full_name: string;
  /** @minLength 1 */
  role: string;
}

export interface SubmissionEvaluation {
  readonly id: number;
  readonly scores: readonly ScoreItem[];
  readonly total_score: number;
  readonly final_score: number;
  comment?: string;
  readonly created_at: string;
}

export interface SubmissionEvaluationRequest {
  comment?: string;
}

export interface SubmissionRequest {
  round: number;
  /**
   * @minLength 1
   * @maxLength 200
   */
  github_url: string;
  /** @maxLength 200 */
  demo_video_url?: string;
  demo_video_file?: Blob;
  /** @maxLength 200 */
  live_demo_url?: string;
  description?: string;
}

export interface Team {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 254 */
  email: string;
  readonly captain_id: number;
  is_public?: boolean;
  /** @maxLength 255 */
  organization?: string;
  /** @maxLength 100 */
  contact_telegram?: string;
  /** @maxLength 100 */
  contact_discord?: string;
  /** @nullable */
  readonly banner: string | null;
  readonly members: readonly TeamMember[];
  readonly is_member: boolean;
  readonly can_request_to_join: boolean;
  readonly is_in_active_tournament: boolean;
}

export interface TeamBanner {
  /** @nullable */
  banner?: string | null;
}

export interface TeamBannerRequest {
  /** @nullable */
  banner?: Blob | null;
}

export interface TeamDetailResponse {
  detail: string;
}

export interface TeamDetailResponseRequest {
  /** @minLength 1 */
  detail: string;
}

export interface TeamInvitation {
  readonly id: number;
  readonly user: TeamMember;
  status?: StatusB9dEnum;
  readonly created_at: string;
  /** @nullable */
  responded_at?: string | null;
  readonly invited_by_id: number;
}

export interface TeamInvitationInbox {
  readonly id: number;
  readonly team: TeamSummary;
  status?: StatusB9dEnum;
  readonly created_at: string;
  /** @nullable */
  responded_at?: string | null;
  readonly invited_by: TeamMember;
}

export interface TeamJoinRequest {
  readonly id: number;
  readonly user: TeamMember;
  status?: TeamJoinStatusEnum;
  readonly created_at: string;
  /** @nullable */
  reviewed_at?: string | null;
  readonly reviewed_by_id: number;
}

/**
 * * `pending` - Pending
* `accepted` - Accepted
* `declined` - Declined
 */
export type TeamJoinStatusEnum = typeof TeamJoinStatusEnum[keyof typeof TeamJoinStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamJoinStatusEnum = {
  pending: 'pending',
  accepted: 'accepted',
  declined: 'declined',
} as const;

export interface TeamMember {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 255 */
  full_name?: string;
  role?: RoleB96Enum;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  readonly avatar_frame_url: string | null;
}

export interface TeamMemberRequest {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @minLength 1
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /** @maxLength 255 */
  full_name?: string;
  role?: RoleB96Enum;
  /** @nullable */
  avatar?: Blob | null;
}

export interface TeamRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  is_public?: boolean;
  /** @maxLength 255 */
  organization?: string;
  /** @maxLength 100 */
  contact_telegram?: string;
  /** @maxLength 100 */
  contact_discord?: string;
  member_ids?: number[];
}

/**
 * @nullable
 */
export type TeamStatsTopPlayer = TopPlayer | null;

export interface TeamStats {
  team_id: number;
  team_name: string;
  total_tournaments: number;
  wins: number;
  losses: number;
  win_rate: number;
  average_member_evaluation_score: number;
  active_members_count: number;
  /** @nullable */
  top_player: TeamStatsTopPlayer;
}

export interface TeamSummary {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  is_public?: boolean;
}

export interface TeamSummaryRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  is_public?: boolean;
}

export interface TeamUserList {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 255 */
  full_name?: string;
  role?: RoleB96Enum;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  readonly avatar_frame_url: string | null;
}

export interface TokenRefreshRequestRequest {
  /** @minLength 1 */
  refresh: string;
}

export interface TokenRefreshResponse {
  access: string;
}

export interface TopPlayer {
  id: number;
  username: string;
  average_evaluation_score: number;
}

export interface TopTeam {
  team_id: number;
  team_name: string;
  /** @nullable */
  rank: number | null;
  average_score: number;
}

export interface TournamentAdmin {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  description: string;
  start_date: string;
  end_date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  max_teams?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  min_team_members?: number | null;
  /** @nullable */
  readonly banner: string | null;
  readonly status: StatusD67Enum;
  readonly rounds: readonly RoundShort[];
  readonly registered_team: TeamSummary;
}

export interface TournamentAdminRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** @minLength 1 */
  description: string;
  start_date: string;
  end_date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  max_teams?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  min_team_members?: number | null;
}

export interface TournamentArchiveDetail {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  description: string;
  start_date: string;
  end_date: string;
  status?: StatusD67Enum;
  /** @nullable */
  banner?: string | null;
  readonly rounds: readonly RoundShort[];
  readonly teams: readonly TeamSummary[];
  readonly standings: readonly ArchiveStanding[];
}

export interface TournamentArchiveList {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  description: string;
  start_date: string;
  end_date: string;
  status?: StatusD67Enum;
  /** @nullable */
  banner?: string | null;
  readonly teams: readonly TeamSummary[];
  readonly standings: readonly ArchiveStanding[];
}

export interface TournamentBanner {
  /** @nullable */
  banner?: string | null;
}

export interface TournamentBannerRequest {
  /** @nullable */
  banner?: Blob | null;
}

export interface TournamentLeaderboardResponse {
  tournament_id: number;
  is_snapshot: boolean;
  rankings: TournamentRankingItem[];
}

export interface TournamentListResponse {
  data: TournamentPublic[];
  total: number;
}

export interface TournamentPublic {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  description: string;
  start_date: string;
  end_date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  max_teams?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  min_team_members?: number | null;
  /** @nullable */
  banner?: string | null;
  status?: StatusD67Enum;
  readonly rounds: readonly RoundShort[];
  readonly registered_team: TeamSummary;
}

export interface TournamentRankingItem {
  team_id: number;
  team_name: string;
  total_score: number;
  rank: number;
  rounds: RoundSummary[];
}

export interface TournamentStats {
  tournament_id: number;
  tournament_name: string;
  total_registered_teams: number;
  total_registered_players: number;
  fill_rate: number;
  completed_matches: number;
  total_matches: number;
  average_evaluation_score: number;
  top_teams: TopTeam[];
}

export interface TournamentTeamLeaveRequest {
  team_id: number;
}

export interface TournamentTeamRegistration {
  readonly id: number;
  readonly tournament: number;
  team: number;
  readonly team_name: string;
  is_active?: boolean;
  is_disqualified?: boolean;
  /** @nullable */
  disqualification_reason?: string | null;
  readonly created_at: string;
}

export interface TournamentTeamRegistrationCreateRequest {
  team_id: number;
}

export type TournamentTeamRegistrationListMembersItem = {[key: string]: unknown};

export interface TournamentTeamRegistrationList {
  id: number;
  registration_id: number;
  name: string;
  readonly members_count: number;
  readonly members: readonly TournamentTeamRegistrationListMembersItem[];
  is_public: boolean;
  is_active?: boolean;
  is_disqualified: boolean;
  /** @nullable */
  disqualification_reason?: string | null;
}

/**
 * * `event` - event
* `round` - round
 */
export type TypeBd0Enum = typeof TypeBd0Enum[keyof typeof TypeBd0Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeBd0Enum = {
  event: 'event',
  round: 'round',
} as const;

export interface UnreadCountResponse {
  unread_count: number;
}

export interface User {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  readonly email: string;
  role?: RoleB96Enum;
  /** @maxLength 255 */
  full_name?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  city?: string;
  readonly avatar: string;
  /** Designates whether the user can log into this admin site. */
  readonly is_staff: boolean;
  /** @nullable */
  readonly avatar_frame_url: string | null;
  readonly created_at: string;
  readonly needs_onboarding: boolean;
  readonly teams: readonly UserTeam[];
}

export interface UserAvatarUpdate {
  /** @nullable */
  avatar?: string | null;
}

export interface UserAvatarUpdateRequest {
  /** @nullable */
  avatar?: Blob | null;
}

export interface UserLookup {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email: string;
}

export interface UserPointsBalance {
  user_id: number;
  balance: number;
  updated_at: string;
}

export interface UserShort {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 255 */
  full_name?: string;
}

export interface UserTeam {
  id: number;
  name: string;
  contact_telegram: string;
  contact_discord: string;
}

export interface UserUpdateRequest {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @minLength 1
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  role?: RoleB96Enum;
  /** @maxLength 255 */
  full_name?: string;
  /** @maxLength 20 */
  phone?: string;
  /** @maxLength 100 */
  city?: string;
  /** @minLength 1 */
  password?: string;
  redeem_code?: string;
}

export type ListRoleActivationCodesParams = {
/**
 * Filter by role: jury, organizer, admin
 */
role?: string;
};

export type ListUsersParams = {
/**
 * Filter by username, email, or full name
 */
search?: string;
};

export type ListCertificatesParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Search by username, full name, certificate number or unique code (admin only)
 */
search?: string;
};

export type ListCertificateTemplatesParams = {
/**
 * Pass "true" to disable pagination
 */
nopage?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListJuryAssignmentsParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Filter by round ID
 */
round_id?: number;
};

export type ListAvailableJuryParams = {
/**
 * Include jurors already assigned to this round
 */
include_assigned?: boolean;
};

export type ListMyDigitalInventoryParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListNewsParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListNotificationsParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListAdminUserPointsTransactionsParams = {
/**
 * Order by field
 */
ordering?: ListAdminUserPointsTransactionsOrdering;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListAdminUserPointsTransactionsOrdering = typeof ListAdminUserPointsTransactionsOrdering[keyof typeof ListAdminUserPointsTransactionsOrdering];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAdminUserPointsTransactionsOrdering = {
  '-amount': '-amount',
  '-created_at': '-created_at',
  amount: 'amount',
  created_at: 'created_at',
} as const;

export type ListMyPointsTransactionsParams = {
/**
 * Order by field
 */
ordering?: ListMyPointsTransactionsOrdering;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListMyPointsTransactionsOrdering = typeof ListMyPointsTransactionsOrdering[keyof typeof ListMyPointsTransactionsOrdering];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListMyPointsTransactionsOrdering = {
  '-amount': '-amount',
  '-created_at': '-created_at',
  amount: 'amount',
  created_at: 'created_at',
} as const;

export type SchemaRetrieveParams = {
format?: SchemaRetrieveFormat;
lang?: SchemaRetrieveLang;
};

export type SchemaRetrieveFormat = typeof SchemaRetrieveFormat[keyof typeof SchemaRetrieveFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SchemaRetrieveFormat = {
  json: 'json',
  yaml: 'yaml',
} as const;

export type SchemaRetrieveLang = typeof SchemaRetrieveLang[keyof typeof SchemaRetrieveLang];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SchemaRetrieveLang = {
  af: 'af',
  ar: 'ar',
  'ar-dz': 'ar-dz',
  ast: 'ast',
  az: 'az',
  be: 'be',
  bg: 'bg',
  bn: 'bn',
  br: 'br',
  bs: 'bs',
  ca: 'ca',
  ckb: 'ckb',
  cs: 'cs',
  cy: 'cy',
  da: 'da',
  de: 'de',
  dsb: 'dsb',
  el: 'el',
  en: 'en',
  'en-au': 'en-au',
  'en-gb': 'en-gb',
  eo: 'eo',
  es: 'es',
  'es-ar': 'es-ar',
  'es-co': 'es-co',
  'es-mx': 'es-mx',
  'es-ni': 'es-ni',
  'es-ve': 'es-ve',
  et: 'et',
  eu: 'eu',
  fa: 'fa',
  fi: 'fi',
  fr: 'fr',
  fy: 'fy',
  ga: 'ga',
  gd: 'gd',
  gl: 'gl',
  he: 'he',
  hi: 'hi',
  hr: 'hr',
  hsb: 'hsb',
  hu: 'hu',
  hy: 'hy',
  ia: 'ia',
  id: 'id',
  ig: 'ig',
  io: 'io',
  is: 'is',
  it: 'it',
  ja: 'ja',
  ka: 'ka',
  kab: 'kab',
  kk: 'kk',
  km: 'km',
  kn: 'kn',
  ko: 'ko',
  ky: 'ky',
  lb: 'lb',
  lt: 'lt',
  lv: 'lv',
  mk: 'mk',
  ml: 'ml',
  mn: 'mn',
  mr: 'mr',
  ms: 'ms',
  my: 'my',
  nb: 'nb',
  ne: 'ne',
  nl: 'nl',
  nn: 'nn',
  os: 'os',
  pa: 'pa',
  pl: 'pl',
  pt: 'pt',
  'pt-br': 'pt-br',
  ro: 'ro',
  ru: 'ru',
  sk: 'sk',
  sl: 'sl',
  sq: 'sq',
  sr: 'sr',
  'sr-latn': 'sr-latn',
  sv: 'sv',
  sw: 'sw',
  ta: 'ta',
  te: 'te',
  tg: 'tg',
  th: 'th',
  tk: 'tk',
  tr: 'tr',
  tt: 'tt',
  udm: 'udm',
  ug: 'ug',
  uk: 'uk',
  ur: 'ur',
  uz: 'uz',
  vi: 'vi',
  'zh-hans': 'zh-hans',
  'zh-hant': 'zh-hant',
} as const;

export type SchemaRetrieve200One = {[key: string]: unknown};

export type SchemaRetrieve200Two = {[key: string]: unknown};

export type SchemaRetrieve200Three = {[key: string]: unknown};

export type SchemaRetrieve200Four = {[key: string]: unknown};

export type ListAdminAvatarFramesParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListAdminCategoriesParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListAdminOrdersParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListAdminProductsParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListAvatarFramesParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListMyOrdersParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
};

export type ListProductsParams = {
/**
 * Filter by category ID
 */
category?: number;
/**
 * Order by field
 */
ordering?: ListProductsOrdering;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Filter by product type
 */
product_type?: ListProductsProductType;
/**
 * Search by name
 */
search?: string;
};

export type ListProductsOrdering = typeof ListProductsOrdering[keyof typeof ListProductsOrdering];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListProductsOrdering = {
  '-name': '-name',
  '-price': '-price',
  name: 'name',
  price: 'price',
} as const;

export type ListProductsProductType = typeof ListProductsProductType[keyof typeof ListProductsProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListProductsProductType = {
  digital: 'digital',
  physical: 'physical',
} as const;

export type ListTournamentsParams = {
createdAt?: string;
endAt?: string;
page?: number;
page_size?: number;
searchQuery?: string;
startAt?: string;
/**
 * Comma-separated statuses
 */
status?: string;
};

export type ListTournamentTeamsParams = {
/**
 * all | disqualified | active (default)
 */
status?: string;
};

export type ListRoundsParams = {
/**
 * Comma-separated statuses
 */
status?: string;
};

export type GetTeamActiveTournamentParams = {
team_id: number;
};

export type GetCurrentTaskParams = {
tournament_id?: number;
};

export type ListEventsParams = {
tournament?: number;
};

