/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponsePermissionDenied,
  ErrorResponseValidationError,
  ListNewsParams,
  NewsArticle,
  PaginatedNewsArticleList,
  PatchedNewsArticle
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const listNews = (
    params?: MaybeRef<ListNewsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedNewsArticleList>(
      {url: `http://localhost:8000/api/news/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListNewsQueryKey = (params?: MaybeRef<ListNewsParams>,) => {
    return [
    'http:','localhost:8000','api','news', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListNewsQueryOptions = <TData = Awaited<ReturnType<typeof listNews>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListNewsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListNewsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNews>>> = ({ signal }) => listNews(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNews>>, TError, TData> 
}

export type ListNewsQueryResult = NonNullable<Awaited<ReturnType<typeof listNews>>>
export type ListNewsQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListNews<TData = Awaited<ReturnType<typeof listNews>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListNewsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listNews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListNewsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createNews = (
    newsArticle: MaybeRef<NonReadonly<NewsArticle>>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      newsArticle = unref(newsArticle);
      
      return customInstance<NewsArticle>(
      {url: `http://localhost:8000/api/news/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: newsArticle, signal
    },
      options);
    }
  


export const getCreateNewsMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNews>>, TError,{data: BodyType<NonReadonly<NewsArticle>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createNews>>, TError,{data: BodyType<NonReadonly<NewsArticle>>}, TContext> => {

const mutationKey = ['createNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNews>>, {data: BodyType<NonReadonly<NewsArticle>>}> = (props) => {
          const {data} = props ?? {};

          return  createNews(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNewsMutationResult = NonNullable<Awaited<ReturnType<typeof createNews>>>
    export type CreateNewsMutationBody = BodyType<NonReadonly<NewsArticle>>
    export type CreateNewsMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateNews = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNews>>, TError,{data: BodyType<NonReadonly<NewsArticle>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createNews>>,
        TError,
        {data: BodyType<NonReadonly<NewsArticle>>},
        TContext
      > => {

      const mutationOptions = getCreateNewsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getNews = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<NewsArticle>(
      {url: `http://localhost:8000/api/news/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetNewsQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','news',id
    ] as const;
    }

    
export const getGetNewsQueryOptions = <TData = Awaited<ReturnType<typeof getNews>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetNewsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNews>>> = ({ signal }) => getNews(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData> 
}

export type GetNewsQueryResult = NonNullable<Awaited<ReturnType<typeof getNews>>>
export type GetNewsQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>



export function useGetNews<TData = Awaited<ReturnType<typeof getNews>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNewsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceNews = (
    id: MaybeRef<number>,
    newsArticle: MaybeRef<NonReadonly<NewsArticle>>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
newsArticle = unref(newsArticle);
      
      return customInstance<NewsArticle>(
      {url: `http://localhost:8000/api/news/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: newsArticle
    },
      options);
    }
  


export const getReplaceNewsMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceNews>>, TError,{id: number;data: BodyType<NonReadonly<NewsArticle>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceNews>>, TError,{id: number;data: BodyType<NonReadonly<NewsArticle>>}, TContext> => {

const mutationKey = ['replaceNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceNews>>, {id: number;data: BodyType<NonReadonly<NewsArticle>>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceNews(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceNewsMutationResult = NonNullable<Awaited<ReturnType<typeof replaceNews>>>
    export type ReplaceNewsMutationBody = BodyType<NonReadonly<NewsArticle>>
    export type ReplaceNewsMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useReplaceNews = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceNews>>, TError,{id: number;data: BodyType<NonReadonly<NewsArticle>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceNews>>,
        TError,
        {id: number;data: BodyType<NonReadonly<NewsArticle>>},
        TContext
      > => {

      const mutationOptions = getReplaceNewsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateNews = (
    id: MaybeRef<number>,
    patchedNewsArticle: MaybeRef<NonReadonly<PatchedNewsArticle>>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
patchedNewsArticle = unref(patchedNewsArticle);
      
      return customInstance<NewsArticle>(
      {url: `http://localhost:8000/api/news/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedNewsArticle
    },
      options);
    }
  


export const getUpdateNewsMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNews>>, TError,{id: number;data: BodyType<NonReadonly<PatchedNewsArticle>>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateNews>>, TError,{id: number;data: BodyType<NonReadonly<PatchedNewsArticle>>}, TContext> => {

const mutationKey = ['updateNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNews>>, {id: number;data: BodyType<NonReadonly<PatchedNewsArticle>>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateNews(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNewsMutationResult = NonNullable<Awaited<ReturnType<typeof updateNews>>>
    export type UpdateNewsMutationBody = BodyType<NonReadonly<PatchedNewsArticle>>
    export type UpdateNewsMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateNews = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNews>>, TError,{id: number;data: BodyType<NonReadonly<PatchedNewsArticle>>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateNews>>,
        TError,
        {id: number;data: BodyType<NonReadonly<PatchedNewsArticle>>},
        TContext
      > => {

      const mutationOptions = getUpdateNewsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteNews = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/news/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteNewsMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNews>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNews>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteNews'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNews>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteNews(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNewsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNews>>>
    
    export type DeleteNewsMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteNews = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNews>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteNews>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteNewsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    