/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AvatarFrame,
  AvatarFrameRequest,
  Category,
  CategoryRequest,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponsePermissionDenied,
  ErrorResponseValidationError,
  ListAdminAvatarFramesParams,
  ListAdminCategoriesParams,
  ListAdminOrdersParams,
  ListAdminProductsParams,
  ListAvatarFramesParams,
  ListMyOrdersParams,
  ListProductsParams,
  Order,
  PaginatedAvatarFrameList,
  PaginatedCategoryList,
  PaginatedOrderList,
  PaginatedProductList,
  PatchedAdminOrderStatusUpdateRequest,
  PatchedAvatarFrameRequest,
  PatchedCategoryRequest,
  PatchedProductRequest,
  Product,
  ProductRequest,
  PurchaseRequest
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const listAdminAvatarFrames = (
    params?: MaybeRef<ListAdminAvatarFramesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedAvatarFrameList>(
      {url: `http://localhost:8000/api/shop/admin/avatar-frames/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListAdminAvatarFramesQueryKey = (params?: MaybeRef<ListAdminAvatarFramesParams>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','avatar-frames', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAdminAvatarFramesQueryOptions = <TData = Awaited<ReturnType<typeof listAdminAvatarFrames>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(params?: MaybeRef<ListAdminAvatarFramesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAvatarFrames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListAdminAvatarFramesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminAvatarFrames>>> = ({ signal }) => listAdminAvatarFrames(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminAvatarFrames>>, TError, TData> 
}

export type ListAdminAvatarFramesQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminAvatarFrames>>>
export type ListAdminAvatarFramesQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>



export function useListAdminAvatarFrames<TData = Awaited<ReturnType<typeof listAdminAvatarFrames>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(
 params?: MaybeRef<ListAdminAvatarFramesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminAvatarFrames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminAvatarFramesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createAdminAvatarFrame = (
    avatarFrameRequest: MaybeRef<AvatarFrameRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      avatarFrameRequest = unref(avatarFrameRequest);
      
      return customInstance<AvatarFrame>(
      {url: `http://localhost:8000/api/shop/admin/avatar-frames/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: avatarFrameRequest, signal
    },
      options);
    }
  


export const getCreateAdminAvatarFrameMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminAvatarFrame>>, TError,{data: BodyType<AvatarFrameRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminAvatarFrame>>, TError,{data: BodyType<AvatarFrameRequest>}, TContext> => {

const mutationKey = ['createAdminAvatarFrame'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminAvatarFrame>>, {data: BodyType<AvatarFrameRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createAdminAvatarFrame(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminAvatarFrameMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminAvatarFrame>>>
    export type CreateAdminAvatarFrameMutationBody = BodyType<AvatarFrameRequest>
    export type CreateAdminAvatarFrameMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateAdminAvatarFrame = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminAvatarFrame>>, TError,{data: BodyType<AvatarFrameRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createAdminAvatarFrame>>,
        TError,
        {data: BodyType<AvatarFrameRequest>},
        TContext
      > => {

      const mutationOptions = getCreateAdminAvatarFrameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminAvatarFrame = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<AvatarFrame>(
      {url: `http://localhost:8000/api/shop/admin/avatar-frames/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminAvatarFrameQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','avatar-frames',id
    ] as const;
    }

    
export const getGetAdminAvatarFrameQueryOptions = <TData = Awaited<ReturnType<typeof getAdminAvatarFrame>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAvatarFrame>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAdminAvatarFrameQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminAvatarFrame>>> = ({ signal }) => getAdminAvatarFrame(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminAvatarFrame>>, TError, TData> 
}

export type GetAdminAvatarFrameQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminAvatarFrame>>>
export type GetAdminAvatarFrameQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>



export function useGetAdminAvatarFrame<TData = Awaited<ReturnType<typeof getAdminAvatarFrame>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminAvatarFrame>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminAvatarFrameQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceAdminAvatarFrame = (
    id: MaybeRef<number>,
    avatarFrameRequest: MaybeRef<AvatarFrameRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
avatarFrameRequest = unref(avatarFrameRequest);
      
      return customInstance<AvatarFrame>(
      {url: `http://localhost:8000/api/shop/admin/avatar-frames/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: avatarFrameRequest
    },
      options);
    }
  


export const getReplaceAdminAvatarFrameMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceAdminAvatarFrame>>, TError,{id: number;data: BodyType<AvatarFrameRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceAdminAvatarFrame>>, TError,{id: number;data: BodyType<AvatarFrameRequest>}, TContext> => {

const mutationKey = ['replaceAdminAvatarFrame'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceAdminAvatarFrame>>, {id: number;data: BodyType<AvatarFrameRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceAdminAvatarFrame(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceAdminAvatarFrameMutationResult = NonNullable<Awaited<ReturnType<typeof replaceAdminAvatarFrame>>>
    export type ReplaceAdminAvatarFrameMutationBody = BodyType<AvatarFrameRequest>
    export type ReplaceAdminAvatarFrameMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useReplaceAdminAvatarFrame = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceAdminAvatarFrame>>, TError,{id: number;data: BodyType<AvatarFrameRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceAdminAvatarFrame>>,
        TError,
        {id: number;data: BodyType<AvatarFrameRequest>},
        TContext
      > => {

      const mutationOptions = getReplaceAdminAvatarFrameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateAdminAvatarFrame = (
    id: MaybeRef<number>,
    patchedAvatarFrameRequest: MaybeRef<PatchedAvatarFrameRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
patchedAvatarFrameRequest = unref(patchedAvatarFrameRequest);
      
      return customInstance<AvatarFrame>(
      {url: `http://localhost:8000/api/shop/admin/avatar-frames/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedAvatarFrameRequest
    },
      options);
    }
  


export const getUpdateAdminAvatarFrameMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminAvatarFrame>>, TError,{id: number;data: BodyType<PatchedAvatarFrameRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminAvatarFrame>>, TError,{id: number;data: BodyType<PatchedAvatarFrameRequest>}, TContext> => {

const mutationKey = ['updateAdminAvatarFrame'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminAvatarFrame>>, {id: number;data: BodyType<PatchedAvatarFrameRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateAdminAvatarFrame(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminAvatarFrameMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminAvatarFrame>>>
    export type UpdateAdminAvatarFrameMutationBody = BodyType<PatchedAvatarFrameRequest>
    export type UpdateAdminAvatarFrameMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateAdminAvatarFrame = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminAvatarFrame>>, TError,{id: number;data: BodyType<PatchedAvatarFrameRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateAdminAvatarFrame>>,
        TError,
        {id: number;data: BodyType<PatchedAvatarFrameRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateAdminAvatarFrameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminAvatarFrame = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/shop/admin/avatar-frames/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminAvatarFrameMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminAvatarFrame>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminAvatarFrame>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAdminAvatarFrame'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminAvatarFrame>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminAvatarFrame(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminAvatarFrameMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminAvatarFrame>>>
    
    export type DeleteAdminAvatarFrameMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteAdminAvatarFrame = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminAvatarFrame>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteAdminAvatarFrame>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAdminAvatarFrameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAdminCategories = (
    params?: MaybeRef<ListAdminCategoriesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedCategoryList>(
      {url: `http://localhost:8000/api/shop/admin/categories/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListAdminCategoriesQueryKey = (params?: MaybeRef<ListAdminCategoriesParams>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','categories', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAdminCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listAdminCategories>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(params?: MaybeRef<ListAdminCategoriesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCategories>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListAdminCategoriesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminCategories>>> = ({ signal }) => listAdminCategories(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminCategories>>, TError, TData> 
}

export type ListAdminCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminCategories>>>
export type ListAdminCategoriesQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>



export function useListAdminCategories<TData = Awaited<ReturnType<typeof listAdminCategories>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(
 params?: MaybeRef<ListAdminCategoriesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminCategories>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createAdminCategory = (
    categoryRequest: MaybeRef<CategoryRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      categoryRequest = unref(categoryRequest);
      
      return customInstance<Category>(
      {url: `http://localhost:8000/api/shop/admin/categories/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryRequest, signal
    },
      options);
    }
  


export const getCreateAdminCategoryMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminCategory>>, TError,{data: BodyType<CategoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminCategory>>, TError,{data: BodyType<CategoryRequest>}, TContext> => {

const mutationKey = ['createAdminCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminCategory>>, {data: BodyType<CategoryRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createAdminCategory(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminCategory>>>
    export type CreateAdminCategoryMutationBody = BodyType<CategoryRequest>
    export type CreateAdminCategoryMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateAdminCategory = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminCategory>>, TError,{data: BodyType<CategoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createAdminCategory>>,
        TError,
        {data: BodyType<CategoryRequest>},
        TContext
      > => {

      const mutationOptions = getCreateAdminCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminCategory = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<Category>(
      {url: `http://localhost:8000/api/shop/admin/categories/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminCategoryQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','categories',id
    ] as const;
    }

    
export const getGetAdminCategoryQueryOptions = <TData = Awaited<ReturnType<typeof getAdminCategory>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCategory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAdminCategoryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminCategory>>> = ({ signal }) => getAdminCategory(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminCategory>>, TError, TData> 
}

export type GetAdminCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminCategory>>>
export type GetAdminCategoryQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>



export function useGetAdminCategory<TData = Awaited<ReturnType<typeof getAdminCategory>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminCategory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminCategoryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceAdminCategory = (
    id: MaybeRef<number>,
    categoryRequest: MaybeRef<CategoryRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
categoryRequest = unref(categoryRequest);
      
      return customInstance<Category>(
      {url: `http://localhost:8000/api/shop/admin/categories/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryRequest
    },
      options);
    }
  


export const getReplaceAdminCategoryMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceAdminCategory>>, TError,{id: number;data: BodyType<CategoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceAdminCategory>>, TError,{id: number;data: BodyType<CategoryRequest>}, TContext> => {

const mutationKey = ['replaceAdminCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceAdminCategory>>, {id: number;data: BodyType<CategoryRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceAdminCategory(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceAdminCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof replaceAdminCategory>>>
    export type ReplaceAdminCategoryMutationBody = BodyType<CategoryRequest>
    export type ReplaceAdminCategoryMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useReplaceAdminCategory = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceAdminCategory>>, TError,{id: number;data: BodyType<CategoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceAdminCategory>>,
        TError,
        {id: number;data: BodyType<CategoryRequest>},
        TContext
      > => {

      const mutationOptions = getReplaceAdminCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateAdminCategory = (
    id: MaybeRef<number>,
    patchedCategoryRequest: MaybeRef<PatchedCategoryRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
patchedCategoryRequest = unref(patchedCategoryRequest);
      
      return customInstance<Category>(
      {url: `http://localhost:8000/api/shop/admin/categories/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedCategoryRequest
    },
      options);
    }
  


export const getUpdateAdminCategoryMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminCategory>>, TError,{id: number;data: BodyType<PatchedCategoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminCategory>>, TError,{id: number;data: BodyType<PatchedCategoryRequest>}, TContext> => {

const mutationKey = ['updateAdminCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminCategory>>, {id: number;data: BodyType<PatchedCategoryRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateAdminCategory(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminCategory>>>
    export type UpdateAdminCategoryMutationBody = BodyType<PatchedCategoryRequest>
    export type UpdateAdminCategoryMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateAdminCategory = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminCategory>>, TError,{id: number;data: BodyType<PatchedCategoryRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateAdminCategory>>,
        TError,
        {id: number;data: BodyType<PatchedCategoryRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateAdminCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminCategory = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/shop/admin/categories/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminCategoryMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCategory>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCategory>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAdminCategory'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminCategory>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminCategory(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminCategory>>>
    
    export type DeleteAdminCategoryMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteAdminCategory = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminCategory>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteAdminCategory>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAdminCategoryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAdminOrders = (
    params?: MaybeRef<ListAdminOrdersParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedOrderList>(
      {url: `http://localhost:8000/api/shop/admin/orders/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListAdminOrdersQueryKey = (params?: MaybeRef<ListAdminOrdersParams>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','orders', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAdminOrdersQueryOptions = <TData = Awaited<ReturnType<typeof listAdminOrders>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(params?: MaybeRef<ListAdminOrdersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListAdminOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminOrders>>> = ({ signal }) => listAdminOrders(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminOrders>>, TError, TData> 
}

export type ListAdminOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminOrders>>>
export type ListAdminOrdersQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>



export function useListAdminOrders<TData = Awaited<ReturnType<typeof listAdminOrders>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(
 params?: MaybeRef<ListAdminOrdersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const cancelAdminOrder = (
    orderId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      orderId = unref(orderId);
      
      return customInstance<Order>(
      {url: `http://localhost:8000/api/shop/admin/orders/${orderId}/cancel/`, method: 'POST', signal
    },
      options);
    }
  


export const getCancelAdminOrderMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelAdminOrder>>, TError,{orderId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelAdminOrder>>, TError,{orderId: number}, TContext> => {

const mutationKey = ['cancelAdminOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelAdminOrder>>, {orderId: number}> = (props) => {
          const {orderId} = props ?? {};

          return  cancelAdminOrder(orderId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelAdminOrderMutationResult = NonNullable<Awaited<ReturnType<typeof cancelAdminOrder>>>
    
    export type CancelAdminOrderMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useCancelAdminOrder = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelAdminOrder>>, TError,{orderId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof cancelAdminOrder>>,
        TError,
        {orderId: number},
        TContext
      > => {

      const mutationOptions = getCancelAdminOrderMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateAdminOrderStatus = (
    orderId: MaybeRef<number>,
    patchedAdminOrderStatusUpdateRequest: MaybeRef<PatchedAdminOrderStatusUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      orderId = unref(orderId);
patchedAdminOrderStatusUpdateRequest = unref(patchedAdminOrderStatusUpdateRequest);
      
      return customInstance<Order>(
      {url: `http://localhost:8000/api/shop/admin/orders/${orderId}/status/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedAdminOrderStatusUpdateRequest
    },
      options);
    }
  


export const getUpdateAdminOrderStatusMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminOrderStatus>>, TError,{orderId: number;data: BodyType<PatchedAdminOrderStatusUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminOrderStatus>>, TError,{orderId: number;data: BodyType<PatchedAdminOrderStatusUpdateRequest>}, TContext> => {

const mutationKey = ['updateAdminOrderStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminOrderStatus>>, {orderId: number;data: BodyType<PatchedAdminOrderStatusUpdateRequest>}> = (props) => {
          const {orderId,data} = props ?? {};

          return  updateAdminOrderStatus(orderId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminOrderStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminOrderStatus>>>
    export type UpdateAdminOrderStatusMutationBody = BodyType<PatchedAdminOrderStatusUpdateRequest>
    export type UpdateAdminOrderStatusMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateAdminOrderStatus = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminOrderStatus>>, TError,{orderId: number;data: BodyType<PatchedAdminOrderStatusUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateAdminOrderStatus>>,
        TError,
        {orderId: number;data: BodyType<PatchedAdminOrderStatusUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateAdminOrderStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAdminProducts = (
    params?: MaybeRef<ListAdminProductsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedProductList>(
      {url: `http://localhost:8000/api/shop/admin/products/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListAdminProductsQueryKey = (params?: MaybeRef<ListAdminProductsParams>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','products', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAdminProductsQueryOptions = <TData = Awaited<ReturnType<typeof listAdminProducts>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(params?: MaybeRef<ListAdminProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListAdminProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminProducts>>> = ({ signal }) => listAdminProducts(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminProducts>>, TError, TData> 
}

export type ListAdminProductsQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminProducts>>>
export type ListAdminProductsQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>



export function useListAdminProducts<TData = Awaited<ReturnType<typeof listAdminProducts>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(
 params?: MaybeRef<ListAdminProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createAdminProduct = (
    productRequest: MaybeRef<ProductRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      productRequest = unref(productRequest);
      const formData = new FormData();
formData.append(`name`, productRequest.name)
if(productRequest.description !== undefined) {
 formData.append(`description`, productRequest.description)
 }
formData.append(`price`, productRequest.price.toString())
if(productRequest.stock_quantity !== undefined) {
 formData.append(`stock_quantity`, productRequest.stock_quantity.toString())
 }
formData.append(`category_id`, productRequest.category_id.toString())
if(productRequest.product_type !== undefined) {
 formData.append(`product_type`, productRequest.product_type)
 }
if(productRequest.avatar_frame_id !== undefined && productRequest.avatar_frame_id !== null) {
 formData.append(`avatar_frame_id`, productRequest.avatar_frame_id.toString())
 }
if(productRequest.avatar_frame_file !== undefined) {
 formData.append(`avatar_frame_file`, productRequest.avatar_frame_file)
 }
if(productRequest.digital_asset_url !== undefined) {
 formData.append(`digital_asset_url`, productRequest.digital_asset_url)
 }
if(productRequest.uploaded_images !== undefined) {
 productRequest.uploaded_images.forEach(value => formData.append(`uploaded_images`, value));
 }
if(productRequest.is_active !== undefined) {
 formData.append(`is_active`, productRequest.is_active.toString())
 }

      return customInstance<Product>(
      {url: `http://localhost:8000/api/shop/admin/products/`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getCreateAdminProductMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminProduct>>, TError,{data: BodyType<ProductRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAdminProduct>>, TError,{data: BodyType<ProductRequest>}, TContext> => {

const mutationKey = ['createAdminProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAdminProduct>>, {data: BodyType<ProductRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createAdminProduct(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAdminProductMutationResult = NonNullable<Awaited<ReturnType<typeof createAdminProduct>>>
    export type CreateAdminProductMutationBody = BodyType<ProductRequest>
    export type CreateAdminProductMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateAdminProduct = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAdminProduct>>, TError,{data: BodyType<ProductRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createAdminProduct>>,
        TError,
        {data: BodyType<ProductRequest>},
        TContext
      > => {

      const mutationOptions = getCreateAdminProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getAdminProduct = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<Product>(
      {url: `http://localhost:8000/api/shop/admin/products/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminProductQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','shop','admin','products',id
    ] as const;
    }

    
export const getGetAdminProductQueryOptions = <TData = Awaited<ReturnType<typeof getAdminProduct>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAdminProductQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminProduct>>> = ({ signal }) => getAdminProduct(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminProduct>>, TError, TData> 
}

export type GetAdminProductQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminProduct>>>
export type GetAdminProductQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>



export function useGetAdminProduct<TData = Awaited<ReturnType<typeof getAdminProduct>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminProductQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceAdminProduct = (
    id: MaybeRef<number>,
    productRequest: MaybeRef<ProductRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
productRequest = unref(productRequest);
      
      return customInstance<Product>(
      {url: `http://localhost:8000/api/shop/admin/products/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: productRequest
    },
      options);
    }
  


export const getReplaceAdminProductMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceAdminProduct>>, TError,{id: number;data: BodyType<ProductRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceAdminProduct>>, TError,{id: number;data: BodyType<ProductRequest>}, TContext> => {

const mutationKey = ['replaceAdminProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceAdminProduct>>, {id: number;data: BodyType<ProductRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceAdminProduct(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceAdminProductMutationResult = NonNullable<Awaited<ReturnType<typeof replaceAdminProduct>>>
    export type ReplaceAdminProductMutationBody = BodyType<ProductRequest>
    export type ReplaceAdminProductMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useReplaceAdminProduct = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceAdminProduct>>, TError,{id: number;data: BodyType<ProductRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceAdminProduct>>,
        TError,
        {id: number;data: BodyType<ProductRequest>},
        TContext
      > => {

      const mutationOptions = getReplaceAdminProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateAdminProduct = (
    id: MaybeRef<number>,
    patchedProductRequest: MaybeRef<PatchedProductRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
patchedProductRequest = unref(patchedProductRequest);
      
      return customInstance<Product>(
      {url: `http://localhost:8000/api/shop/admin/products/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedProductRequest
    },
      options);
    }
  


export const getUpdateAdminProductMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminProduct>>, TError,{id: number;data: BodyType<PatchedProductRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminProduct>>, TError,{id: number;data: BodyType<PatchedProductRequest>}, TContext> => {

const mutationKey = ['updateAdminProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminProduct>>, {id: number;data: BodyType<PatchedProductRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateAdminProduct(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminProduct>>>
    export type UpdateAdminProductMutationBody = BodyType<PatchedProductRequest>
    export type UpdateAdminProductMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateAdminProduct = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminProduct>>, TError,{id: number;data: BodyType<PatchedProductRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateAdminProduct>>,
        TError,
        {id: number;data: BodyType<PatchedProductRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateAdminProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteAdminProduct = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/shop/admin/products/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteAdminProductMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminProduct>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminProduct>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteAdminProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminProduct>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteAdminProduct(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminProduct>>>
    
    export type DeleteAdminProductMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteAdminProduct = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminProduct>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteAdminProduct>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteAdminProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAvatarFrames = (
    params?: MaybeRef<ListAvatarFramesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedAvatarFrameList>(
      {url: `http://localhost:8000/api/shop/avatar-frames/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListAvatarFramesQueryKey = (params?: MaybeRef<ListAvatarFramesParams>,) => {
    return [
    'http:','localhost:8000','api','shop','avatar-frames', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAvatarFramesQueryOptions = <TData = Awaited<ReturnType<typeof listAvatarFrames>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListAvatarFramesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAvatarFrames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListAvatarFramesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAvatarFrames>>> = ({ signal }) => listAvatarFrames(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAvatarFrames>>, TError, TData> 
}

export type ListAvatarFramesQueryResult = NonNullable<Awaited<ReturnType<typeof listAvatarFrames>>>
export type ListAvatarFramesQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListAvatarFrames<TData = Awaited<ReturnType<typeof listAvatarFrames>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListAvatarFramesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAvatarFrames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAvatarFramesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const listMyOrders = (
    params?: MaybeRef<ListMyOrdersParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedOrderList>(
      {url: `http://localhost:8000/api/shop/orders/my/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListMyOrdersQueryKey = (params?: MaybeRef<ListMyOrdersParams>,) => {
    return [
    'http:','localhost:8000','api','shop','orders','my', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListMyOrdersQueryOptions = <TData = Awaited<ReturnType<typeof listMyOrders>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListMyOrdersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListMyOrdersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyOrders>>> = ({ signal }) => listMyOrders(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyOrders>>, TError, TData> 
}

export type ListMyOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof listMyOrders>>>
export type ListMyOrdersQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListMyOrders<TData = Awaited<ReturnType<typeof listMyOrders>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListMyOrdersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const cancelMyOrder = (
    orderId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      orderId = unref(orderId);
      
      return customInstance<Order>(
      {url: `http://localhost:8000/api/shop/orders/my/${orderId}/cancel/`, method: 'POST', signal
    },
      options);
    }
  


export const getCancelMyOrderMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelMyOrder>>, TError,{orderId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cancelMyOrder>>, TError,{orderId: number}, TContext> => {

const mutationKey = ['cancelMyOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelMyOrder>>, {orderId: number}> = (props) => {
          const {orderId} = props ?? {};

          return  cancelMyOrder(orderId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CancelMyOrderMutationResult = NonNullable<Awaited<ReturnType<typeof cancelMyOrder>>>
    
    export type CancelMyOrderMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useCancelMyOrder = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cancelMyOrder>>, TError,{orderId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof cancelMyOrder>>,
        TError,
        {orderId: number},
        TContext
      > => {

      const mutationOptions = getCancelMyOrderMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listProducts = (
    params?: MaybeRef<ListProductsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedProductList>(
      {url: `http://localhost:8000/api/shop/products/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListProductsQueryKey = (params?: MaybeRef<ListProductsParams>,) => {
    return [
    'http:','localhost:8000','api','shop','products', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListProductsQueryOptions = <TData = Awaited<ReturnType<typeof listProducts>>, TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProducts>>> = ({ signal }) => listProducts(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProducts>>, TError, TData> 
}

export type ListProductsQueryResult = NonNullable<Awaited<ReturnType<typeof listProducts>>>
export type ListProductsQueryError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>



export function useListProducts<TData = Awaited<ReturnType<typeof listProducts>>, TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListProductsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProducts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProductsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const getProduct = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<Product>(
      {url: `http://localhost:8000/api/shop/products/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProductQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','shop','products',id
    ] as const;
    }

    
export const getGetProductQueryOptions = <TData = Awaited<ReturnType<typeof getProduct>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetProductQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduct>>> = ({ signal }) => getProduct(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData> 
}

export type GetProductQueryResult = NonNullable<Awaited<ReturnType<typeof getProduct>>>
export type GetProductQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>



export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const purchaseProduct = (
    purchaseRequest: MaybeRef<PurchaseRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      purchaseRequest = unref(purchaseRequest);
      
      return customInstance<Order>(
      {url: `http://localhost:8000/api/shop/purchase/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: purchaseRequest, signal
    },
      options);
    }
  


export const getPurchaseProductMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseProduct>>, TError,{data: BodyType<PurchaseRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseProduct>>, TError,{data: BodyType<PurchaseRequest>}, TContext> => {

const mutationKey = ['purchaseProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseProduct>>, {data: BodyType<PurchaseRequest>}> = (props) => {
          const {data} = props ?? {};

          return  purchaseProduct(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PurchaseProductMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseProduct>>>
    export type PurchaseProductMutationBody = BodyType<PurchaseRequest>
    export type PurchaseProductMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const usePurchaseProduct = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseProduct>>, TError,{data: BodyType<PurchaseRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof purchaseProduct>>,
        TError,
        {data: BodyType<PurchaseRequest>},
        TContext
      > => {

      const mutationOptions = getPurchaseProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    