# Generated by Django 5.2.4 on 2026-05-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0008_delete_userdigitalinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'digital'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Inventories',
                'ordering': ['-acquired_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='inventory_user_product_unique')],
            },
        ),
    ]
