/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API (Ninja)
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AdminStatsResponse,
  ErrorResponse,
  PlayerStatsResponse,
  TeamStatsResponse,
  TournamentStatsResponse
} from '../backendAPINinja.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Player Stats
 */
export const getPlayerStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PlayerStatsResponse>(
      {url: `http://localhost:8000/api/stats/player`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPlayerStatsQueryKey = () => {
    return [
    'http:','localhost:8000','api','stats','player'
    ] as const;
    }

    
export const getGetPlayerStatsQueryOptions = <TData = Awaited<ReturnType<typeof getPlayerStats>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetPlayerStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayerStats>>> = ({ signal }) => getPlayerStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData> 
}

export type GetPlayerStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getPlayerStats>>>
export type GetPlayerStatsQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get Player Stats
 */

export function useGetPlayerStats<TData = Awaited<ReturnType<typeof getPlayerStats>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlayerStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Get Team Stats
 */
export const getTeamStats = (
    teamId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      teamId = unref(teamId);
      
      return customInstance<TeamStatsResponse>(
      {url: `http://localhost:8000/api/stats/team/${teamId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTeamStatsQueryKey = (teamId?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','stats','team',teamId
    ] as const;
    }

    
export const getGetTeamStatsQueryOptions = <TData = Awaited<ReturnType<typeof getTeamStats>>, TError = ErrorType<ErrorResponse>>(teamId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetTeamStatsQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeamStats>>> = ({ signal }) => getTeamStats(teamId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(teamId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeamStats>>, TError, TData> 
}

export type GetTeamStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getTeamStats>>>
export type GetTeamStatsQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get Team Stats
 */

export function useGetTeamStats<TData = Awaited<ReturnType<typeof getTeamStats>>, TError = ErrorType<ErrorResponse>>(
 teamId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeamStatsQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Get Tournament Stats
 */
export const getTournamentStats = (
    tournamentId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      tournamentId = unref(tournamentId);
      
      return customInstance<TournamentStatsResponse>(
      {url: `http://localhost:8000/api/stats/tournament/${tournamentId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTournamentStatsQueryKey = (tournamentId?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','stats','tournament',tournamentId
    ] as const;
    }

    
export const getGetTournamentStatsQueryOptions = <TData = Awaited<ReturnType<typeof getTournamentStats>>, TError = ErrorType<ErrorResponse>>(tournamentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTournamentStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetTournamentStatsQueryKey(tournamentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTournamentStats>>> = ({ signal }) => getTournamentStats(tournamentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(tournamentId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTournamentStats>>, TError, TData> 
}

export type GetTournamentStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getTournamentStats>>>
export type GetTournamentStatsQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get Tournament Stats
 */

export function useGetTournamentStats<TData = Awaited<ReturnType<typeof getTournamentStats>>, TError = ErrorType<ErrorResponse>>(
 tournamentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTournamentStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTournamentStatsQueryOptions(tournamentId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Get Admin Stats
 */
export const getAdminStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AdminStatsResponse>(
      {url: `http://localhost:8000/api/stats/admin`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminStatsQueryKey = () => {
    return [
    'http:','localhost:8000','api','stats','admin'
    ] as const;
    }

    
export const getGetAdminStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminStats>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAdminStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({ signal }) => getAdminStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData> 
}

export type GetAdminStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminStats>>>
export type GetAdminStatsQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get Admin Stats
 */

export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




