/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AdminStats,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponsePermissionDenied,
  PlayerStats,
  TeamStats,
  TournamentStats
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns high-level system metrics including user growth and role distributions.
 * @summary Get platform-wide admin statistics
 */
export const getAdminStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AdminStats>(
      {url: `http://localhost:8000/api/stats/admin/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminStatsQueryKey = () => {
    return [
    'http:','localhost:8000','api','stats','admin'
    ] as const;
    }

    
export const getGetAdminStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminStats>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAdminStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({ signal }) => getAdminStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData> 
}

export type GetAdminStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminStats>>>
export type GetAdminStatsQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>


/**
 * @summary Get platform-wide admin statistics
 */

export function useGetAdminStats<TData = Awaited<ReturnType<typeof getAdminStats>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Calculates win rates and average scores for the authenticated user based on their team performance.
 * @summary Get personal player statistics
 */
export const getPlayerStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PlayerStats>(
      {url: `http://localhost:8000/api/stats/player/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPlayerStatsQueryKey = () => {
    return [
    'http:','localhost:8000','api','stats','player'
    ] as const;
    }

    
export const getGetPlayerStatsQueryOptions = <TData = Awaited<ReturnType<typeof getPlayerStats>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetPlayerStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayerStats>>> = ({ signal }) => getPlayerStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData> 
}

export type GetPlayerStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getPlayerStats>>>
export type GetPlayerStatsQueryError = ErrorType<ErrorResponseNotAuthenticated>


/**
 * @summary Get personal player statistics
 */

export function useGetPlayerStats<TData = Awaited<ReturnType<typeof getPlayerStats>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPlayerStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Returns performance metrics for a specific team. Access restricted to members or admins.
 * @summary Get team statistics
 */
export const getTeamStats = (
    teamId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      teamId = unref(teamId);
      
      return customInstance<TeamStats>(
      {url: `http://localhost:8000/api/stats/team/${teamId}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTeamStatsQueryKey = (teamId?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','stats','team',teamId
    ] as const;
    }

    
export const getGetTeamStatsQueryOptions = <TData = Awaited<ReturnType<typeof getTeamStats>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(teamId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetTeamStatsQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeamStats>>> = ({ signal }) => getTeamStats(teamId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(teamId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeamStats>>, TError, TData> 
}

export type GetTeamStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getTeamStats>>>
export type GetTeamStatsQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>


/**
 * @summary Get team statistics
 */

export function useGetTeamStats<TData = Awaited<ReturnType<typeof getTeamStats>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 teamId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeamStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeamStatsQueryOptions(teamId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Returns detailed breakdown of tournament registration, match completion, and leaderboard top 3.
 * @summary Get tournament organizer statistics
 */
export const getTournamentStats = (
    tournamentId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      tournamentId = unref(tournamentId);
      
      return customInstance<TournamentStats>(
      {url: `http://localhost:8000/api/stats/tournament/${tournamentId}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTournamentStatsQueryKey = (tournamentId?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','stats','tournament',tournamentId
    ] as const;
    }

    
export const getGetTournamentStatsQueryOptions = <TData = Awaited<ReturnType<typeof getTournamentStats>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(tournamentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTournamentStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetTournamentStatsQueryKey(tournamentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTournamentStats>>> = ({ signal }) => getTournamentStats(tournamentId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(tournamentId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTournamentStats>>, TError, TData> 
}

export type GetTournamentStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getTournamentStats>>>
export type GetTournamentStatsQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>


/**
 * @summary Get tournament organizer statistics
 */

export function useGetTournamentStats<TData = Awaited<ReturnType<typeof getTournamentStats>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>>(
 tournamentId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTournamentStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTournamentStatsQueryOptions(tournamentId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



