/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Backend API (Ninja)
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  CertificateRequest,
  CertificateResponse,
  CertificateTemplateResponse,
  CertificateVerifyResponse,
  CreateCertificateTemplateBody,
  CreateCertificateTemplateParams,
  ErrorResponse,
  ListCertificateTemplatesParams,
  ListCertificatesParams,
  PagedCertificateResponse,
  PagedCertificateTemplateResponse,
  ReplaceCertificateTemplateBody,
  ReplaceCertificateTemplateParams,
  UpdateCertificateTemplateBody,
  UpdateCertificateTemplateParams
} from '../backendAPINinja.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Templates
 */
export const listCertificateTemplates = (
    params?: MaybeRef<ListCertificateTemplatesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PagedCertificateTemplateResponse>(
      {url: `http://localhost:8000/api/certificates/certificate-templates`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListCertificateTemplatesQueryKey = (params?: MaybeRef<ListCertificateTemplatesParams>,) => {
    return [
    'http:','localhost:8000','api','certificates','certificate-templates', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListCertificateTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof listCertificateTemplates>>, TError = ErrorType<ErrorResponse>>(params?: MaybeRef<ListCertificateTemplatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificateTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListCertificateTemplatesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCertificateTemplates>>> = ({ signal }) => listCertificateTemplates(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCertificateTemplates>>, TError, TData> 
}

export type ListCertificateTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof listCertificateTemplates>>>
export type ListCertificateTemplatesQueryError = ErrorType<ErrorResponse>


/**
 * @summary List Templates
 */

export function useListCertificateTemplates<TData = Awaited<ReturnType<typeof listCertificateTemplates>>, TError = ErrorType<ErrorResponse>>(
 params?: MaybeRef<ListCertificateTemplatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificateTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCertificateTemplatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Create Template
 */
export const createCertificateTemplate = (
    createCertificateTemplateBody: MaybeRef<CreateCertificateTemplateBody>,
    params: MaybeRef<CreateCertificateTemplateParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      createCertificateTemplateBody = unref(createCertificateTemplateBody);
params = unref(params);
      const formData = new FormData();
formData.append(`image`, createCertificateTemplateBody.image)

      return customInstance<CertificateTemplateResponse>(
      {url: `http://localhost:8000/api/certificates/certificate-templates`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params: unref(params), signal
    },
      options);
    }
  


export const getCreateCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificateTemplate>>, TError,{data: BodyType<CreateCertificateTemplateBody>;params: CreateCertificateTemplateParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCertificateTemplate>>, TError,{data: BodyType<CreateCertificateTemplateBody>;params: CreateCertificateTemplateParams}, TContext> => {

const mutationKey = ['createCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCertificateTemplate>>, {data: BodyType<CreateCertificateTemplateBody>;params: CreateCertificateTemplateParams}> = (props) => {
          const {data,params} = props ?? {};

          return  createCertificateTemplate(data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createCertificateTemplate>>>
    export type CreateCertificateTemplateMutationBody = BodyType<CreateCertificateTemplateBody>
    export type CreateCertificateTemplateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create Template
 */
export const useCreateCertificateTemplate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificateTemplate>>, TError,{data: BodyType<CreateCertificateTemplateBody>;params: CreateCertificateTemplateParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createCertificateTemplate>>,
        TError,
        {data: BodyType<CreateCertificateTemplateBody>;params: CreateCertificateTemplateParams},
        TContext
      > => {

      const mutationOptions = getCreateCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Template
 */
export const getCertificateTemplate = (
    templateId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      templateId = unref(templateId);
      
      return customInstance<CertificateTemplateResponse>(
      {url: `http://localhost:8000/api/certificates/certificate-templates/${templateId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCertificateTemplateQueryKey = (templateId?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','certificates','certificate-templates',templateId
    ] as const;
    }

    
export const getGetCertificateTemplateQueryOptions = <TData = Awaited<ReturnType<typeof getCertificateTemplate>>, TError = ErrorType<ErrorResponse>>(templateId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificateTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetCertificateTemplateQueryKey(templateId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCertificateTemplate>>> = ({ signal }) => getCertificateTemplate(templateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(templateId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCertificateTemplate>>, TError, TData> 
}

export type GetCertificateTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof getCertificateTemplate>>>
export type GetCertificateTemplateQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get Template
 */

export function useGetCertificateTemplate<TData = Awaited<ReturnType<typeof getCertificateTemplate>>, TError = ErrorType<ErrorResponse>>(
 templateId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificateTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCertificateTemplateQueryOptions(templateId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Update Template
 */
export const updateCertificateTemplate = (
    templateId: MaybeRef<number>,
    updateCertificateTemplateBody: MaybeRef<UpdateCertificateTemplateBody>,
    params?: MaybeRef<UpdateCertificateTemplateParams>,
 options?: SecondParameter<typeof customInstance>,) => {
      templateId = unref(templateId);
updateCertificateTemplateBody = unref(updateCertificateTemplateBody);
params = unref(params);
      const formData = new FormData();
if(updateCertificateTemplateBody.image !== undefined) {
 formData.append(`image`, updateCertificateTemplateBody.image)
 }

      return customInstance<CertificateTemplateResponse>(
      {url: `http://localhost:8000/api/certificates/certificate-templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params: unref(params)
    },
      options);
    }
  


export const getUpdateCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificateTemplate>>, TError,{templateId: number;data: BodyType<UpdateCertificateTemplateBody>;params?: UpdateCertificateTemplateParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCertificateTemplate>>, TError,{templateId: number;data: BodyType<UpdateCertificateTemplateBody>;params?: UpdateCertificateTemplateParams}, TContext> => {

const mutationKey = ['updateCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCertificateTemplate>>, {templateId: number;data: BodyType<UpdateCertificateTemplateBody>;params?: UpdateCertificateTemplateParams}> = (props) => {
          const {templateId,data,params} = props ?? {};

          return  updateCertificateTemplate(templateId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateCertificateTemplate>>>
    export type UpdateCertificateTemplateMutationBody = BodyType<UpdateCertificateTemplateBody>
    export type UpdateCertificateTemplateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update Template
 */
export const useUpdateCertificateTemplate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificateTemplate>>, TError,{templateId: number;data: BodyType<UpdateCertificateTemplateBody>;params?: UpdateCertificateTemplateParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateCertificateTemplate>>,
        TError,
        {templateId: number;data: BodyType<UpdateCertificateTemplateBody>;params?: UpdateCertificateTemplateParams},
        TContext
      > => {

      const mutationOptions = getUpdateCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Template
 */
export const replaceCertificateTemplate = (
    templateId: MaybeRef<number>,
    replaceCertificateTemplateBody: MaybeRef<ReplaceCertificateTemplateBody>,
    params?: MaybeRef<ReplaceCertificateTemplateParams>,
 options?: SecondParameter<typeof customInstance>,) => {
      templateId = unref(templateId);
replaceCertificateTemplateBody = unref(replaceCertificateTemplateBody);
params = unref(params);
      const formData = new FormData();
if(replaceCertificateTemplateBody.image !== undefined) {
 formData.append(`image`, replaceCertificateTemplateBody.image)
 }

      return customInstance<CertificateTemplateResponse>(
      {url: `http://localhost:8000/api/certificates/certificate-templates/${templateId}`, method: 'PUT',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData,
        params: unref(params)
    },
      options);
    }
  


export const getReplaceCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceCertificateTemplate>>, TError,{templateId: number;data: BodyType<ReplaceCertificateTemplateBody>;params?: ReplaceCertificateTemplateParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceCertificateTemplate>>, TError,{templateId: number;data: BodyType<ReplaceCertificateTemplateBody>;params?: ReplaceCertificateTemplateParams}, TContext> => {

const mutationKey = ['replaceCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceCertificateTemplate>>, {templateId: number;data: BodyType<ReplaceCertificateTemplateBody>;params?: ReplaceCertificateTemplateParams}> = (props) => {
          const {templateId,data,params} = props ?? {};

          return  replaceCertificateTemplate(templateId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof replaceCertificateTemplate>>>
    export type ReplaceCertificateTemplateMutationBody = BodyType<ReplaceCertificateTemplateBody>
    export type ReplaceCertificateTemplateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update Template
 */
export const useReplaceCertificateTemplate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceCertificateTemplate>>, TError,{templateId: number;data: BodyType<ReplaceCertificateTemplateBody>;params?: ReplaceCertificateTemplateParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceCertificateTemplate>>,
        TError,
        {templateId: number;data: BodyType<ReplaceCertificateTemplateBody>;params?: ReplaceCertificateTemplateParams},
        TContext
      > => {

      const mutationOptions = getReplaceCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Template
 */
export const deleteCertificateTemplate = (
    templateId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      templateId = unref(templateId);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/certificates/certificate-templates/${templateId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificateTemplate>>, TError,{templateId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCertificateTemplate>>, TError,{templateId: number}, TContext> => {

const mutationKey = ['deleteCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCertificateTemplate>>, {templateId: number}> = (props) => {
          const {templateId} = props ?? {};

          return  deleteCertificateTemplate(templateId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCertificateTemplate>>>
    
    export type DeleteCertificateTemplateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete Template
 */
export const useDeleteCertificateTemplate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificateTemplate>>, TError,{templateId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteCertificateTemplate>>,
        TError,
        {templateId: number},
        TContext
      > => {

      const mutationOptions = getDeleteCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List Certificates
 */
export const listCertificates = (
    params?: MaybeRef<ListCertificatesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PagedCertificateResponse>(
      {url: `http://localhost:8000/api/certificates`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListCertificatesQueryKey = (params?: MaybeRef<ListCertificatesParams>,) => {
    return [
    'http:','localhost:8000','api','certificates', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListCertificatesQueryOptions = <TData = Awaited<ReturnType<typeof listCertificates>>, TError = ErrorType<ErrorResponse>>(params?: MaybeRef<ListCertificatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListCertificatesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCertificates>>> = ({ signal }) => listCertificates(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCertificates>>, TError, TData> 
}

export type ListCertificatesQueryResult = NonNullable<Awaited<ReturnType<typeof listCertificates>>>
export type ListCertificatesQueryError = ErrorType<ErrorResponse>


/**
 * @summary List Certificates
 */

export function useListCertificates<TData = Awaited<ReturnType<typeof listCertificates>>, TError = ErrorType<ErrorResponse>>(
 params?: MaybeRef<ListCertificatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCertificatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Create Certificate
 */
export const createCertificate = (
    certificateRequest: MaybeRef<CertificateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      certificateRequest = unref(certificateRequest);
      
      return customInstance<CertificateResponse>(
      {url: `http://localhost:8000/api/certificates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: certificateRequest, signal
    },
      options);
    }
  


export const getCreateCertificateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificate>>, TError,{data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCertificate>>, TError,{data: BodyType<CertificateRequest>}, TContext> => {

const mutationKey = ['createCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCertificate>>, {data: BodyType<CertificateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createCertificate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof createCertificate>>>
    export type CreateCertificateMutationBody = BodyType<CertificateRequest>
    export type CreateCertificateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Create Certificate
 */
export const useCreateCertificate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificate>>, TError,{data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createCertificate>>,
        TError,
        {data: BodyType<CertificateRequest>},
        TContext
      > => {

      const mutationOptions = getCreateCertificateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get Certificate
 */
export const getCertificate = (
    uniqueCode: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uniqueCode = unref(uniqueCode);
      
      return customInstance<CertificateResponse>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCertificateQueryKey = (uniqueCode?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','certificates',uniqueCode
    ] as const;
    }

    
export const getGetCertificateQueryOptions = <TData = Awaited<ReturnType<typeof getCertificate>>, TError = ErrorType<ErrorResponse>>(uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetCertificateQueryKey(uniqueCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCertificate>>> = ({ signal }) => getCertificate(uniqueCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uniqueCode))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCertificate>>, TError, TData> 
}

export type GetCertificateQueryResult = NonNullable<Awaited<ReturnType<typeof getCertificate>>>
export type GetCertificateQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get Certificate
 */

export function useGetCertificate<TData = Awaited<ReturnType<typeof getCertificate>>, TError = ErrorType<ErrorResponse>>(
 uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCertificateQueryOptions(uniqueCode,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Update Certificate
 */
export const updateCertificate = (
    uniqueCode: MaybeRef<string>,
    certificateRequest: MaybeRef<CertificateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      uniqueCode = unref(uniqueCode);
certificateRequest = unref(certificateRequest);
      
      return customInstance<CertificateResponse>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: certificateRequest
    },
      options);
    }
  


export const getUpdateCertificateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificate>>, TError,{uniqueCode: string;data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCertificate>>, TError,{uniqueCode: string;data: BodyType<CertificateRequest>}, TContext> => {

const mutationKey = ['updateCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCertificate>>, {uniqueCode: string;data: BodyType<CertificateRequest>}> = (props) => {
          const {uniqueCode,data} = props ?? {};

          return  updateCertificate(uniqueCode,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof updateCertificate>>>
    export type UpdateCertificateMutationBody = BodyType<CertificateRequest>
    export type UpdateCertificateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update Certificate
 */
export const useUpdateCertificate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificate>>, TError,{uniqueCode: string;data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateCertificate>>,
        TError,
        {uniqueCode: string;data: BodyType<CertificateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateCertificateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete Certificate
 */
export const deleteCertificate = (
    uniqueCode: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,) => {
      uniqueCode = unref(uniqueCode);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCertificateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificate>>, TError,{uniqueCode: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCertificate>>, TError,{uniqueCode: string}, TContext> => {

const mutationKey = ['deleteCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCertificate>>, {uniqueCode: string}> = (props) => {
          const {uniqueCode} = props ?? {};

          return  deleteCertificate(uniqueCode,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCertificate>>>
    
    export type DeleteCertificateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Delete Certificate
 */
export const useDeleteCertificate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificate>>, TError,{uniqueCode: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteCertificate>>,
        TError,
        {uniqueCode: string},
        TContext
      > => {

      const mutationOptions = getDeleteCertificateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary View Certificate Pdf
 */
export const viewCertificatePdf = (
    uniqueCode: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uniqueCode = unref(uniqueCode);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}/view`, method: 'GET', signal
    },
      options);
    }
  



export const getViewCertificatePdfQueryKey = (uniqueCode?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','certificates',uniqueCode,'view'
    ] as const;
    }

    
export const getViewCertificatePdfQueryOptions = <TData = Awaited<ReturnType<typeof viewCertificatePdf>>, TError = ErrorType<ErrorResponse>>(uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof viewCertificatePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getViewCertificatePdfQueryKey(uniqueCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof viewCertificatePdf>>> = ({ signal }) => viewCertificatePdf(uniqueCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uniqueCode))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof viewCertificatePdf>>, TError, TData> 
}

export type ViewCertificatePdfQueryResult = NonNullable<Awaited<ReturnType<typeof viewCertificatePdf>>>
export type ViewCertificatePdfQueryError = ErrorType<ErrorResponse>


/**
 * @summary View Certificate Pdf
 */

export function useViewCertificatePdf<TData = Awaited<ReturnType<typeof viewCertificatePdf>>, TError = ErrorType<ErrorResponse>>(
 uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof viewCertificatePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getViewCertificatePdfQueryOptions(uniqueCode,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * @summary Verify Certificate
 */
export const verifyCertificate = (
    code: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      code = unref(code);
      
      return customInstance<CertificateVerifyResponse>(
      {url: `http://localhost:8000/api/certificates/verify/${code}`, method: 'GET', signal
    },
      options);
    }
  



export const getVerifyCertificateQueryKey = (code?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','certificates','verify',code
    ] as const;
    }

    
export const getVerifyCertificateQueryOptions = <TData = Awaited<ReturnType<typeof verifyCertificate>>, TError = ErrorType<unknown>>(code: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getVerifyCertificateQueryKey(code);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyCertificate>>> = ({ signal }) => verifyCertificate(code, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(code))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyCertificate>>, TError, TData> 
}

export type VerifyCertificateQueryResult = NonNullable<Awaited<ReturnType<typeof verifyCertificate>>>
export type VerifyCertificateQueryError = ErrorType<unknown>


/**
 * @summary Verify Certificate
 */

export function useVerifyCertificate<TData = Awaited<ReturnType<typeof verifyCertificate>>, TError = ErrorType<unknown>>(
 code: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifyCertificateQueryOptions(code,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




