/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  Certificate,
  CertificateRequest,
  CertificateTemplate,
  CertificateTemplateRequest,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponsePermissionDenied,
  ErrorResponseValidationError,
  ListCertificateTemplatesParams,
  ListCertificatesParams,
  PaginatedCertificateList,
  PaginatedCertificateTemplateList,
  PatchedCertificateRequest,
  PatchedCertificateTemplateRequest
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const listCertificates = (
    params?: MaybeRef<ListCertificatesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedCertificateList>(
      {url: `http://localhost:8000/api/certificates/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListCertificatesQueryKey = (params?: MaybeRef<ListCertificatesParams>,) => {
    return [
    'http:','localhost:8000','api','certificates', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListCertificatesQueryOptions = <TData = Awaited<ReturnType<typeof listCertificates>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListCertificatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListCertificatesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCertificates>>> = ({ signal }) => listCertificates(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCertificates>>, TError, TData> 
}

export type ListCertificatesQueryResult = NonNullable<Awaited<ReturnType<typeof listCertificates>>>
export type ListCertificatesQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListCertificates<TData = Awaited<ReturnType<typeof listCertificates>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListCertificatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCertificatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createCertificate = (
    certificateRequest: MaybeRef<CertificateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      certificateRequest = unref(certificateRequest);
      
      return customInstance<Certificate>(
      {url: `http://localhost:8000/api/certificates/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: certificateRequest, signal
    },
      options);
    }
  


export const getCreateCertificateMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificate>>, TError,{data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCertificate>>, TError,{data: BodyType<CertificateRequest>}, TContext> => {

const mutationKey = ['createCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCertificate>>, {data: BodyType<CertificateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createCertificate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof createCertificate>>>
    export type CreateCertificateMutationBody = BodyType<CertificateRequest>
    export type CreateCertificateMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateCertificate = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificate>>, TError,{data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createCertificate>>,
        TError,
        {data: BodyType<CertificateRequest>},
        TContext
      > => {

      const mutationOptions = getCreateCertificateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCertificate = (
    uniqueCode: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uniqueCode = unref(uniqueCode);
      
      return customInstance<Certificate>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCertificateQueryKey = (uniqueCode?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','certificates',uniqueCode
    ] as const;
    }

    
export const getGetCertificateQueryOptions = <TData = Awaited<ReturnType<typeof getCertificate>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetCertificateQueryKey(uniqueCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCertificate>>> = ({ signal }) => getCertificate(uniqueCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uniqueCode))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCertificate>>, TError, TData> 
}

export type GetCertificateQueryResult = NonNullable<Awaited<ReturnType<typeof getCertificate>>>
export type GetCertificateQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>



export function useGetCertificate<TData = Awaited<ReturnType<typeof getCertificate>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(
 uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCertificateQueryOptions(uniqueCode,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const certificatesUpdate = (
    uniqueCode: MaybeRef<string>,
    certificateRequest: MaybeRef<CertificateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      uniqueCode = unref(uniqueCode);
certificateRequest = unref(certificateRequest);
      
      return customInstance<Certificate>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: certificateRequest
    },
      options);
    }
  


export const getCertificatesUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof certificatesUpdate>>, TError,{uniqueCode: string;data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof certificatesUpdate>>, TError,{uniqueCode: string;data: BodyType<CertificateRequest>}, TContext> => {

const mutationKey = ['certificatesUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof certificatesUpdate>>, {uniqueCode: string;data: BodyType<CertificateRequest>}> = (props) => {
          const {uniqueCode,data} = props ?? {};

          return  certificatesUpdate(uniqueCode,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CertificatesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof certificatesUpdate>>>
    export type CertificatesUpdateMutationBody = BodyType<CertificateRequest>
    export type CertificatesUpdateMutationError = ErrorType<unknown>

    export const useCertificatesUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof certificatesUpdate>>, TError,{uniqueCode: string;data: BodyType<CertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof certificatesUpdate>>,
        TError,
        {uniqueCode: string;data: BodyType<CertificateRequest>},
        TContext
      > => {

      const mutationOptions = getCertificatesUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateCertificate = (
    uniqueCode: MaybeRef<string>,
    patchedCertificateRequest: MaybeRef<PatchedCertificateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      uniqueCode = unref(uniqueCode);
patchedCertificateRequest = unref(patchedCertificateRequest);
      
      return customInstance<Certificate>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedCertificateRequest
    },
      options);
    }
  


export const getUpdateCertificateMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificate>>, TError,{uniqueCode: string;data: BodyType<PatchedCertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCertificate>>, TError,{uniqueCode: string;data: BodyType<PatchedCertificateRequest>}, TContext> => {

const mutationKey = ['updateCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCertificate>>, {uniqueCode: string;data: BodyType<PatchedCertificateRequest>}> = (props) => {
          const {uniqueCode,data} = props ?? {};

          return  updateCertificate(uniqueCode,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof updateCertificate>>>
    export type UpdateCertificateMutationBody = BodyType<PatchedCertificateRequest>
    export type UpdateCertificateMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateCertificate = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificate>>, TError,{uniqueCode: string;data: BodyType<PatchedCertificateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateCertificate>>,
        TError,
        {uniqueCode: string;data: BodyType<PatchedCertificateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateCertificateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteCertificate = (
    uniqueCode: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,) => {
      uniqueCode = unref(uniqueCode);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCertificateMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificate>>, TError,{uniqueCode: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCertificate>>, TError,{uniqueCode: string}, TContext> => {

const mutationKey = ['deleteCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCertificate>>, {uniqueCode: string}> = (props) => {
          const {uniqueCode} = props ?? {};

          return  deleteCertificate(uniqueCode,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCertificate>>>
    
    export type DeleteCertificateMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteCertificate = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificate>>, TError,{uniqueCode: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteCertificate>>,
        TError,
        {uniqueCode: string},
        TContext
      > => {

      const mutationOptions = getDeleteCertificateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const viewCertificatePdf = (
    uniqueCode: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uniqueCode = unref(uniqueCode);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/certificates/${uniqueCode}/view/`, method: 'GET', signal
    },
      options);
    }
  



export const getViewCertificatePdfQueryKey = (uniqueCode?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','certificates',uniqueCode,'view'
    ] as const;
    }

    
export const getViewCertificatePdfQueryOptions = <TData = Awaited<ReturnType<typeof viewCertificatePdf>>, TError = ErrorType<ErrorResponseNotAuthenticated | void>>(uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof viewCertificatePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getViewCertificatePdfQueryKey(uniqueCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof viewCertificatePdf>>> = ({ signal }) => viewCertificatePdf(uniqueCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uniqueCode))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof viewCertificatePdf>>, TError, TData> 
}

export type ViewCertificatePdfQueryResult = NonNullable<Awaited<ReturnType<typeof viewCertificatePdf>>>
export type ViewCertificatePdfQueryError = ErrorType<ErrorResponseNotAuthenticated | void>



export function useViewCertificatePdf<TData = Awaited<ReturnType<typeof viewCertificatePdf>>, TError = ErrorType<ErrorResponseNotAuthenticated | void>>(
 uniqueCode: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof viewCertificatePdf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getViewCertificatePdfQueryOptions(uniqueCode,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const listCertificateTemplates = (
    params?: MaybeRef<ListCertificateTemplatesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedCertificateTemplateList>(
      {url: `http://localhost:8000/api/certificates/templates/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListCertificateTemplatesQueryKey = (params?: MaybeRef<ListCertificateTemplatesParams>,) => {
    return [
    'http:','localhost:8000','api','certificates','templates', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListCertificateTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof listCertificateTemplates>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListCertificateTemplatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificateTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListCertificateTemplatesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCertificateTemplates>>> = ({ signal }) => listCertificateTemplates(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCertificateTemplates>>, TError, TData> 
}

export type ListCertificateTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof listCertificateTemplates>>>
export type ListCertificateTemplatesQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListCertificateTemplates<TData = Awaited<ReturnType<typeof listCertificateTemplates>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListCertificateTemplatesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listCertificateTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListCertificateTemplatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const createCertificateTemplate = (
    certificateTemplateRequest: MaybeRef<CertificateTemplateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      certificateTemplateRequest = unref(certificateTemplateRequest);
      const formData = new FormData();
formData.append(`name`, certificateTemplateRequest.name)
formData.append(`image`, certificateTemplateRequest.image)
if(certificateTemplateRequest.is_default !== undefined) {
 formData.append(`is_default`, certificateTemplateRequest.is_default.toString())
 }

      return customInstance<CertificateTemplate>(
      {url: `http://localhost:8000/api/certificates/templates/`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getCreateCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificateTemplate>>, TError,{data: BodyType<CertificateTemplateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCertificateTemplate>>, TError,{data: BodyType<CertificateTemplateRequest>}, TContext> => {

const mutationKey = ['createCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCertificateTemplate>>, {data: BodyType<CertificateTemplateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createCertificateTemplate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createCertificateTemplate>>>
    export type CreateCertificateTemplateMutationBody = BodyType<CertificateTemplateRequest>
    export type CreateCertificateTemplateMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useCreateCertificateTemplate = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCertificateTemplate>>, TError,{data: BodyType<CertificateTemplateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createCertificateTemplate>>,
        TError,
        {data: BodyType<CertificateTemplateRequest>},
        TContext
      > => {

      const mutationOptions = getCreateCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getCertificateTemplate = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<CertificateTemplate>(
      {url: `http://localhost:8000/api/certificates/templates/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCertificateTemplateQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','certificates','templates',id
    ] as const;
    }

    
export const getGetCertificateTemplateQueryOptions = <TData = Awaited<ReturnType<typeof getCertificateTemplate>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificateTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetCertificateTemplateQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCertificateTemplate>>> = ({ signal }) => getCertificateTemplate(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCertificateTemplate>>, TError, TData> 
}

export type GetCertificateTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof getCertificateTemplate>>>
export type GetCertificateTemplateQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>



export function useGetCertificateTemplate<TData = Awaited<ReturnType<typeof getCertificateTemplate>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCertificateTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCertificateTemplateQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceCertificateTemplate = (
    id: MaybeRef<number>,
    certificateTemplateRequest: MaybeRef<CertificateTemplateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
certificateTemplateRequest = unref(certificateTemplateRequest);
      const formData = new FormData();
formData.append(`name`, certificateTemplateRequest.name)
formData.append(`image`, certificateTemplateRequest.image)
if(certificateTemplateRequest.is_default !== undefined) {
 formData.append(`is_default`, certificateTemplateRequest.is_default.toString())
 }

      return customInstance<CertificateTemplate>(
      {url: `http://localhost:8000/api/certificates/templates/${id}/`, method: 'PUT',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getReplaceCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceCertificateTemplate>>, TError,{id: number;data: BodyType<CertificateTemplateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceCertificateTemplate>>, TError,{id: number;data: BodyType<CertificateTemplateRequest>}, TContext> => {

const mutationKey = ['replaceCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceCertificateTemplate>>, {id: number;data: BodyType<CertificateTemplateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  replaceCertificateTemplate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof replaceCertificateTemplate>>>
    export type ReplaceCertificateTemplateMutationBody = BodyType<CertificateTemplateRequest>
    export type ReplaceCertificateTemplateMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useReplaceCertificateTemplate = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceCertificateTemplate>>, TError,{id: number;data: BodyType<CertificateTemplateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceCertificateTemplate>>,
        TError,
        {id: number;data: BodyType<CertificateTemplateRequest>},
        TContext
      > => {

      const mutationOptions = getReplaceCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateCertificateTemplate = (
    id: MaybeRef<number>,
    patchedCertificateTemplateRequest: MaybeRef<PatchedCertificateTemplateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
patchedCertificateTemplateRequest = unref(patchedCertificateTemplateRequest);
      const formData = new FormData();
if(patchedCertificateTemplateRequest.name !== undefined) {
 formData.append(`name`, patchedCertificateTemplateRequest.name)
 }
if(patchedCertificateTemplateRequest.image !== undefined) {
 formData.append(`image`, patchedCertificateTemplateRequest.image)
 }
if(patchedCertificateTemplateRequest.is_default !== undefined) {
 formData.append(`is_default`, patchedCertificateTemplateRequest.is_default.toString())
 }

      return customInstance<CertificateTemplate>(
      {url: `http://localhost:8000/api/certificates/templates/${id}/`, method: 'PATCH',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getUpdateCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificateTemplate>>, TError,{id: number;data: BodyType<PatchedCertificateTemplateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCertificateTemplate>>, TError,{id: number;data: BodyType<PatchedCertificateTemplateRequest>}, TContext> => {

const mutationKey = ['updateCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCertificateTemplate>>, {id: number;data: BodyType<PatchedCertificateTemplateRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCertificateTemplate(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateCertificateTemplate>>>
    export type UpdateCertificateTemplateMutationBody = BodyType<PatchedCertificateTemplateRequest>
    export type UpdateCertificateTemplateMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useUpdateCertificateTemplate = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCertificateTemplate>>, TError,{id: number;data: BodyType<PatchedCertificateTemplateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateCertificateTemplate>>,
        TError,
        {id: number;data: BodyType<PatchedCertificateTemplateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteCertificateTemplate = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,) => {
      id = unref(id);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/certificates/templates/${id}/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteCertificateTemplateMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificateTemplate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCertificateTemplate>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteCertificateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCertificateTemplate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteCertificateTemplate(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCertificateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCertificateTemplate>>>
    
    export type DeleteCertificateTemplateMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>

    export const useDeleteCertificateTemplate = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCertificateTemplate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteCertificateTemplate>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteCertificateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const verifyCertificate = (
    code: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      code = unref(code);
      
      return customInstance<Certificate>(
      {url: `http://localhost:8000/api/certificates/verify/${code}/`, method: 'GET', signal
    },
      options);
    }
  



export const getVerifyCertificateQueryKey = (code?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','certificates','verify',code
    ] as const;
    }

    
export const getVerifyCertificateQueryOptions = <TData = Awaited<ReturnType<typeof verifyCertificate>>, TError = ErrorType<ErrorResponseNotFound>>(code: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getVerifyCertificateQueryKey(code);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyCertificate>>> = ({ signal }) => verifyCertificate(code, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(code))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof verifyCertificate>>, TError, TData> 
}

export type VerifyCertificateQueryResult = NonNullable<Awaited<ReturnType<typeof verifyCertificate>>>
export type VerifyCertificateQueryError = ErrorType<ErrorResponseNotFound>



export function useVerifyCertificate<TData = Awaited<ReturnType<typeof verifyCertificate>>, TError = ErrorType<ErrorResponseNotFound>>(
 code: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyCertificate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getVerifyCertificateQueryOptions(code,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




