/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ActivationResponse,
  ChangePasswordRequest,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponsePermissionDenied,
  ErrorResponseServiceUnavailable,
  ErrorResponseValidationError,
  GoogleAuthRequest,
  GoogleAuthResponse,
  GoogleCalendarCallbackRequestRequest,
  GoogleCalendarConnectResponse,
  GoogleCalendarStatus,
  ListRoleActivationCodesParams,
  ListUsersParams,
  LoginRequestRequest,
  LoginResponse,
  MessageResponse,
  PasswordResetConfirmRequest,
  PasswordResetRequestRequest,
  PatchedUserAvatarUpdateRequest,
  PatchedUserUpdateRequest,
  Register,
  RegisterRequest,
  RoleActivationCodeGenerateRequest,
  RoleActivationCodeGenerateResponse,
  RoleActivationCodeListResponse,
  TeamUserList,
  TokenRefreshRequestRequest,
  TokenRefreshResponse,
  User,
  UserAvatarUpdate,
  UserAvatarUpdateRequest,
  UserUpdateRequest
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const activateAccount = (
    uidb64: MaybeRef<string>,
    token: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,) => {
      uidb64 = unref(uidb64);
token = unref(token);
      
      return customInstance<ActivationResponse>(
      {url: `http://localhost:8000/api/accounts/activate/${uidb64}/${token}/`, method: 'PATCH'
    },
      options);
    }
  


export const getActivateAccountMutationOptions = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateAccount>>, TError,{uidb64: string;token: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateAccount>>, TError,{uidb64: string;token: string}, TContext> => {

const mutationKey = ['activateAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateAccount>>, {uidb64: string;token: string}> = (props) => {
          const {uidb64,token} = props ?? {};

          return  activateAccount(uidb64,token,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ActivateAccountMutationResult = NonNullable<Awaited<ReturnType<typeof activateAccount>>>
    
    export type ActivateAccountMutationError = ErrorType<ErrorResponseValidationError>

    export const useActivateAccount = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateAccount>>, TError,{uidb64: string;token: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof activateAccount>>,
        TError,
        {uidb64: string;token: string},
        TContext
      > => {

      const mutationOptions = getActivateAccountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const changePassword = (
    changePasswordRequest: MaybeRef<ChangePasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      changePasswordRequest = unref(changePasswordRequest);
      
      return customInstance<MessageResponse>(
      {url: `http://localhost:8000/api/accounts/change-password/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      options);
    }
  


export const getChangePasswordMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: BodyType<ChangePasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = BodyType<ChangePasswordRequest>
    export type ChangePasswordMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useChangePassword = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: BodyType<ChangePasswordRequest>},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const callbackGoogleCalendar = (
    googleCalendarCallbackRequestRequest: MaybeRef<GoogleCalendarCallbackRequestRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      googleCalendarCallbackRequestRequest = unref(googleCalendarCallbackRequestRequest);
      
      return customInstance<GoogleCalendarStatus>(
      {url: `http://localhost:8000/api/accounts/google-calendar/callback/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: googleCalendarCallbackRequestRequest, signal
    },
      options);
    }
  


export const getCallbackGoogleCalendarMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseServiceUnavailable>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof callbackGoogleCalendar>>, TError,{data: BodyType<GoogleCalendarCallbackRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof callbackGoogleCalendar>>, TError,{data: BodyType<GoogleCalendarCallbackRequestRequest>}, TContext> => {

const mutationKey = ['callbackGoogleCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof callbackGoogleCalendar>>, {data: BodyType<GoogleCalendarCallbackRequestRequest>}> = (props) => {
          const {data} = props ?? {};

          return  callbackGoogleCalendar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CallbackGoogleCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof callbackGoogleCalendar>>>
    export type CallbackGoogleCalendarMutationBody = BodyType<GoogleCalendarCallbackRequestRequest>
    export type CallbackGoogleCalendarMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseServiceUnavailable>

    export const useCallbackGoogleCalendar = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseServiceUnavailable>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof callbackGoogleCalendar>>, TError,{data: BodyType<GoogleCalendarCallbackRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof callbackGoogleCalendar>>,
        TError,
        {data: BodyType<GoogleCalendarCallbackRequestRequest>},
        TContext
      > => {

      const mutationOptions = getCallbackGoogleCalendarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const connectGoogleCalendar = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GoogleCalendarConnectResponse>(
      {url: `http://localhost:8000/api/accounts/google-calendar/connect/`, method: 'POST', signal
    },
      options);
    }
  


export const getConnectGoogleCalendarMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseServiceUnavailable>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectGoogleCalendar>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof connectGoogleCalendar>>, TError,void, TContext> => {

const mutationKey = ['connectGoogleCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectGoogleCalendar>>, void> = () => {
          

          return  connectGoogleCalendar(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConnectGoogleCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof connectGoogleCalendar>>>
    
    export type ConnectGoogleCalendarMutationError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseServiceUnavailable>

    export const useConnectGoogleCalendar = <TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseServiceUnavailable>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectGoogleCalendar>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof connectGoogleCalendar>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getConnectGoogleCalendarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const disconnectGoogleCalendar = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GoogleCalendarStatus>(
      {url: `http://localhost:8000/api/accounts/google-calendar/disconnect/`, method: 'POST', signal
    },
      options);
    }
  


export const getDisconnectGoogleCalendarMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnectGoogleCalendar>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof disconnectGoogleCalendar>>, TError,void, TContext> => {

const mutationKey = ['disconnectGoogleCalendar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnectGoogleCalendar>>, void> = () => {
          

          return  disconnectGoogleCalendar(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DisconnectGoogleCalendarMutationResult = NonNullable<Awaited<ReturnType<typeof disconnectGoogleCalendar>>>
    
    export type DisconnectGoogleCalendarMutationError = ErrorType<ErrorResponseNotAuthenticated>

    export const useDisconnectGoogleCalendar = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnectGoogleCalendar>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof disconnectGoogleCalendar>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDisconnectGoogleCalendarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getGoogleCalendarStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GoogleCalendarStatus>(
      {url: `http://localhost:8000/api/accounts/google-calendar/status/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetGoogleCalendarStatusQueryKey = () => {
    return [
    'http:','localhost:8000','api','accounts','google-calendar','status'
    ] as const;
    }

    
export const getGetGoogleCalendarStatusQueryOptions = <TData = Awaited<ReturnType<typeof getGoogleCalendarStatus>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleCalendarStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetGoogleCalendarStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGoogleCalendarStatus>>> = ({ signal }) => getGoogleCalendarStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGoogleCalendarStatus>>, TError, TData> 
}

export type GetGoogleCalendarStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getGoogleCalendarStatus>>>
export type GetGoogleCalendarStatusQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useGetGoogleCalendarStatus<TData = Awaited<ReturnType<typeof getGoogleCalendarStatus>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGoogleCalendarStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGoogleCalendarStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const googleAuth = (
    googleAuthRequest: MaybeRef<GoogleAuthRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      googleAuthRequest = unref(googleAuthRequest);
      
      return customInstance<GoogleAuthResponse>(
      {url: `http://localhost:8000/api/accounts/google-login/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: googleAuthRequest, signal
    },
      options);
    }
  


export const getGoogleAuthMutationOptions = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googleAuth>>, TError,{data: BodyType<GoogleAuthRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof googleAuth>>, TError,{data: BodyType<GoogleAuthRequest>}, TContext> => {

const mutationKey = ['googleAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof googleAuth>>, {data: BodyType<GoogleAuthRequest>}> = (props) => {
          const {data} = props ?? {};

          return  googleAuth(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GoogleAuthMutationResult = NonNullable<Awaited<ReturnType<typeof googleAuth>>>
    export type GoogleAuthMutationBody = BodyType<GoogleAuthRequest>
    export type GoogleAuthMutationError = ErrorType<ErrorResponseValidationError>

    export const useGoogleAuth = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof googleAuth>>, TError,{data: BodyType<GoogleAuthRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof googleAuth>>,
        TError,
        {data: BodyType<GoogleAuthRequest>},
        TContext
      > => {

      const mutationOptions = getGoogleAuthMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const login = (
    loginRequestRequest: MaybeRef<LoginRequestRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      loginRequestRequest = unref(loginRequestRequest);
      
      return customInstance<LoginResponse>(
      {url: `http://localhost:8000/api/accounts/login/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequestRequest, signal
    },
      options);
    }
  


export const getLoginMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequestRequest>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginRequestRequest>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginRequestRequest>
    export type LoginMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useLogin = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginRequestRequest>},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const requestPasswordReset = (
    passwordResetRequestRequest: MaybeRef<PasswordResetRequestRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      passwordResetRequestRequest = unref(passwordResetRequestRequest);
      
      return customInstance<MessageResponse>(
      {url: `http://localhost:8000/api/accounts/password-reset/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetRequestRequest, signal
    },
      options);
    }
  


export const getRequestPasswordResetMutationOptions = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: BodyType<PasswordResetRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: BodyType<PasswordResetRequestRequest>}, TContext> => {

const mutationKey = ['requestPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestPasswordReset>>, {data: BodyType<PasswordResetRequestRequest>}> = (props) => {
          const {data} = props ?? {};

          return  requestPasswordReset(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordReset>>>
    export type RequestPasswordResetMutationBody = BodyType<PasswordResetRequestRequest>
    export type RequestPasswordResetMutationError = ErrorType<ErrorResponseValidationError>

    export const useRequestPasswordReset = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError,{data: BodyType<PasswordResetRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof requestPasswordReset>>,
        TError,
        {data: BodyType<PasswordResetRequestRequest>},
        TContext
      > => {

      const mutationOptions = getRequestPasswordResetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const validatePasswordResetLink = (
    uidb64: MaybeRef<string>,
    token: MaybeRef<string>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uidb64 = unref(uidb64);
token = unref(token);
      
      return customInstance<MessageResponse>(
      {url: `http://localhost:8000/api/accounts/password-reset/${uidb64}/${token}/`, method: 'GET', signal
    },
      options);
    }
  



export const getValidatePasswordResetLinkQueryKey = (uidb64?: MaybeRef<string>,
    token?: MaybeRef<string>,) => {
    return [
    'http:','localhost:8000','api','accounts','password-reset',uidb64,token
    ] as const;
    }

    
export const getValidatePasswordResetLinkQueryOptions = <TData = Awaited<ReturnType<typeof validatePasswordResetLink>>, TError = ErrorType<ErrorResponseValidationError>>(uidb64: MaybeRef<string>,
    token: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof validatePasswordResetLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getValidatePasswordResetLinkQueryKey(uidb64,token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof validatePasswordResetLink>>> = ({ signal }) => validatePasswordResetLink(uidb64,token, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(uidb64) && unref(token))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof validatePasswordResetLink>>, TError, TData> 
}

export type ValidatePasswordResetLinkQueryResult = NonNullable<Awaited<ReturnType<typeof validatePasswordResetLink>>>
export type ValidatePasswordResetLinkQueryError = ErrorType<ErrorResponseValidationError>



export function useValidatePasswordResetLink<TData = Awaited<ReturnType<typeof validatePasswordResetLink>>, TError = ErrorType<ErrorResponseValidationError>>(
 uidb64: MaybeRef<string>,
    token: MaybeRef<string>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof validatePasswordResetLink>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getValidatePasswordResetLinkQueryOptions(uidb64,token,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const confirmPasswordReset = (
    uidb64: MaybeRef<string>,
    token: MaybeRef<string>,
    passwordResetConfirmRequest: MaybeRef<PasswordResetConfirmRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      uidb64 = unref(uidb64);
token = unref(token);
passwordResetConfirmRequest = unref(passwordResetConfirmRequest);
      
      return customInstance<MessageResponse>(
      {url: `http://localhost:8000/api/accounts/password-reset/${uidb64}/${token}/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordResetConfirmRequest, signal
    },
      options);
    }
  


export const getConfirmPasswordResetMutationOptions = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError,{uidb64: string;token: string;data: BodyType<PasswordResetConfirmRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError,{uidb64: string;token: string;data: BodyType<PasswordResetConfirmRequest>}, TContext> => {

const mutationKey = ['confirmPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmPasswordReset>>, {uidb64: string;token: string;data: BodyType<PasswordResetConfirmRequest>}> = (props) => {
          const {uidb64,token,data} = props ?? {};

          return  confirmPasswordReset(uidb64,token,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof confirmPasswordReset>>>
    export type ConfirmPasswordResetMutationBody = BodyType<PasswordResetConfirmRequest>
    export type ConfirmPasswordResetMutationError = ErrorType<ErrorResponseValidationError>

    export const useConfirmPasswordReset = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError,{uidb64: string;token: string;data: BodyType<PasswordResetConfirmRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof confirmPasswordReset>>,
        TError,
        {uidb64: string;token: string;data: BodyType<PasswordResetConfirmRequest>},
        TContext
      > => {

      const mutationOptions = getConfirmPasswordResetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getUserProfile = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<User>(
      {url: `http://localhost:8000/api/accounts/profile/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserProfileQueryKey = () => {
    return [
    'http:','localhost:8000','api','accounts','profile'
    ] as const;
    }

    
export const getGetUserProfileQueryOptions = <TData = Awaited<ReturnType<typeof getUserProfile>>, TError = ErrorType<ErrorResponseNotAuthenticated>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetUserProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfile>>> = ({ signal }) => getUserProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData> 
}

export type GetUserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProfile>>>
export type GetUserProfileQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useGetUserProfile<TData = Awaited<ReturnType<typeof getUserProfile>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfile>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const replaceUserProfile = (
    userUpdateRequest: MaybeRef<UserUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      userUpdateRequest = unref(userUpdateRequest);
      
      return customInstance<User>(
      {url: `http://localhost:8000/api/accounts/profile/`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateRequest
    },
      options);
    }
  


export const getReplaceUserProfileMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceUserProfile>>, TError,{data: BodyType<UserUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof replaceUserProfile>>, TError,{data: BodyType<UserUpdateRequest>}, TContext> => {

const mutationKey = ['replaceUserProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceUserProfile>>, {data: BodyType<UserUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  replaceUserProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceUserProfileMutationResult = NonNullable<Awaited<ReturnType<typeof replaceUserProfile>>>
    export type ReplaceUserProfileMutationBody = BodyType<UserUpdateRequest>
    export type ReplaceUserProfileMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useReplaceUserProfile = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof replaceUserProfile>>, TError,{data: BodyType<UserUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof replaceUserProfile>>,
        TError,
        {data: BodyType<UserUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getReplaceUserProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateUserProfile = (
    patchedUserUpdateRequest: MaybeRef<PatchedUserUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      patchedUserUpdateRequest = unref(patchedUserUpdateRequest);
      
      return customInstance<User>(
      {url: `http://localhost:8000/api/accounts/profile/`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchedUserUpdateRequest
    },
      options);
    }
  


export const getUpdateUserProfileMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserProfile>>, TError,{data: BodyType<PatchedUserUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserProfile>>, TError,{data: BodyType<PatchedUserUpdateRequest>}, TContext> => {

const mutationKey = ['updateUserProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserProfile>>, {data: BodyType<PatchedUserUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  updateUserProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserProfile>>>
    export type UpdateUserProfileMutationBody = BodyType<PatchedUserUpdateRequest>
    export type UpdateUserProfileMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useUpdateUserProfile = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserProfile>>, TError,{data: BodyType<PatchedUserUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUserProfile>>,
        TError,
        {data: BodyType<PatchedUserUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateUserProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteUserProfile = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/accounts/profile/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteUserProfileMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserProfile>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserProfile>>, TError,void, TContext> => {

const mutationKey = ['deleteUserProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserProfile>>, void> = () => {
          

          return  deleteUserProfile(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserProfileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserProfile>>>
    
    export type DeleteUserProfileMutationError = ErrorType<ErrorResponseNotAuthenticated>

    export const useDeleteUserProfile = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserProfile>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteUserProfile>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteUserProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const accountsProfileAvatarUpdate = (
    userAvatarUpdateRequest: MaybeRef<UserAvatarUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      userAvatarUpdateRequest = unref(userAvatarUpdateRequest);
      const formData = new FormData();
if(userAvatarUpdateRequest.avatar !== undefined && userAvatarUpdateRequest.avatar !== null) {
 formData.append(`avatar`, userAvatarUpdateRequest.avatar)
 }

      return customInstance<UserAvatarUpdate>(
      {url: `http://localhost:8000/api/accounts/profile/avatar/`, method: 'PUT',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getAccountsProfileAvatarUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsProfileAvatarUpdate>>, TError,{data: BodyType<UserAvatarUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof accountsProfileAvatarUpdate>>, TError,{data: BodyType<UserAvatarUpdateRequest>}, TContext> => {

const mutationKey = ['accountsProfileAvatarUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof accountsProfileAvatarUpdate>>, {data: BodyType<UserAvatarUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  accountsProfileAvatarUpdate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AccountsProfileAvatarUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof accountsProfileAvatarUpdate>>>
    export type AccountsProfileAvatarUpdateMutationBody = BodyType<UserAvatarUpdateRequest>
    export type AccountsProfileAvatarUpdateMutationError = ErrorType<unknown>

    export const useAccountsProfileAvatarUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof accountsProfileAvatarUpdate>>, TError,{data: BodyType<UserAvatarUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof accountsProfileAvatarUpdate>>,
        TError,
        {data: BodyType<UserAvatarUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getAccountsProfileAvatarUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateUserAvatar = (
    patchedUserAvatarUpdateRequest: MaybeRef<PatchedUserAvatarUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      patchedUserAvatarUpdateRequest = unref(patchedUserAvatarUpdateRequest);
      const formData = new FormData();
if(patchedUserAvatarUpdateRequest.avatar !== undefined && patchedUserAvatarUpdateRequest.avatar !== null) {
 formData.append(`avatar`, patchedUserAvatarUpdateRequest.avatar)
 }

      return customInstance<UserAvatarUpdate>(
      {url: `http://localhost:8000/api/accounts/profile/avatar/`, method: 'PATCH',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getUpdateUserAvatarMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserAvatar>>, TError,{data: BodyType<PatchedUserAvatarUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserAvatar>>, TError,{data: BodyType<PatchedUserAvatarUpdateRequest>}, TContext> => {

const mutationKey = ['updateUserAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserAvatar>>, {data: BodyType<PatchedUserAvatarUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  updateUserAvatar(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserAvatar>>>
    export type UpdateUserAvatarMutationBody = BodyType<PatchedUserAvatarUpdateRequest>
    export type UpdateUserAvatarMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useUpdateUserAvatar = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserAvatar>>, TError,{data: BodyType<PatchedUserAvatarUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUserAvatar>>,
        TError,
        {data: BodyType<PatchedUserAvatarUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateUserAvatarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const deleteUserAvatar = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/accounts/profile/avatar/`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteUserAvatarMutationOptions = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserAvatar>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserAvatar>>, TError,void, TContext> => {

const mutationKey = ['deleteUserAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserAvatar>>, void> = () => {
          

          return  deleteUserAvatar(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserAvatar>>>
    
    export type DeleteUserAvatarMutationError = ErrorType<ErrorResponseNotAuthenticated>

    export const useDeleteUserAvatar = <TError = ErrorType<ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserAvatar>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteUserAvatar>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDeleteUserAvatarMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const registerUser = (
    registerRequest: MaybeRef<RegisterRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      registerRequest = unref(registerRequest);
      
      return customInstance<Register>(
      {url: `http://localhost:8000/api/accounts/register/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      options);
    }
  


export const getRegisterUserMutationOptions = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: BodyType<RegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: BodyType<RegisterRequest>}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: BodyType<RegisterRequest>}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = BodyType<RegisterRequest>
    export type RegisterUserMutationError = ErrorType<ErrorResponseValidationError>

    export const useRegisterUser = <TError = ErrorType<ErrorResponseValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: BodyType<RegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: BodyType<RegisterRequest>},
        TContext
      > => {

      const mutationOptions = getRegisterUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listRoleActivationCodes = (
    params?: MaybeRef<ListRoleActivationCodesParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<RoleActivationCodeListResponse>(
      {url: `http://localhost:8000/api/accounts/role-codes/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListRoleActivationCodesQueryKey = (params?: MaybeRef<ListRoleActivationCodesParams>,) => {
    return [
    'http:','localhost:8000','api','accounts','role-codes', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListRoleActivationCodesQueryOptions = <TData = Awaited<ReturnType<typeof listRoleActivationCodes>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(params?: MaybeRef<ListRoleActivationCodesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoleActivationCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListRoleActivationCodesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRoleActivationCodes>>> = ({ signal }) => listRoleActivationCodes(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRoleActivationCodes>>, TError, TData> 
}

export type ListRoleActivationCodesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoleActivationCodes>>>
export type ListRoleActivationCodesQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>



export function useListRoleActivationCodes<TData = Awaited<ReturnType<typeof listRoleActivationCodes>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>>(
 params?: MaybeRef<ListRoleActivationCodesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoleActivationCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRoleActivationCodesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const generateRoleActivationCodes = (
    roleActivationCodeGenerateRequest: MaybeRef<RoleActivationCodeGenerateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      roleActivationCodeGenerateRequest = unref(roleActivationCodeGenerateRequest);
      
      return customInstance<RoleActivationCodeGenerateResponse>(
      {url: `http://localhost:8000/api/accounts/role-codes/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roleActivationCodeGenerateRequest, signal
    },
      options);
    }
  


export const getGenerateRoleActivationCodesMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateRoleActivationCodes>>, TError,{data: BodyType<RoleActivationCodeGenerateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof generateRoleActivationCodes>>, TError,{data: BodyType<RoleActivationCodeGenerateRequest>}, TContext> => {

const mutationKey = ['generateRoleActivationCodes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateRoleActivationCodes>>, {data: BodyType<RoleActivationCodeGenerateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  generateRoleActivationCodes(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateRoleActivationCodesMutationResult = NonNullable<Awaited<ReturnType<typeof generateRoleActivationCodes>>>
    export type GenerateRoleActivationCodesMutationBody = BodyType<RoleActivationCodeGenerateRequest>
    export type GenerateRoleActivationCodesMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>

    export const useGenerateRoleActivationCodes = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponsePermissionDenied>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateRoleActivationCodes>>, TError,{data: BodyType<RoleActivationCodeGenerateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof generateRoleActivationCodes>>,
        TError,
        {data: BodyType<RoleActivationCodeGenerateRequest>},
        TContext
      > => {

      const mutationOptions = getGenerateRoleActivationCodesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const refreshToken = (
    tokenRefreshRequestRequest: MaybeRef<TokenRefreshRequestRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      tokenRefreshRequestRequest = unref(tokenRefreshRequestRequest);
      
      return customInstance<TokenRefreshResponse>(
      {url: `http://localhost:8000/api/accounts/token/refresh/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRefreshRequestRequest, signal
    },
      options);
    }
  


export const getRefreshTokenMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: BodyType<TokenRefreshRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: BodyType<TokenRefreshRequestRequest>}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: BodyType<TokenRefreshRequestRequest>}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = BodyType<TokenRefreshRequestRequest>
    export type RefreshTokenMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>

    export const useRefreshToken = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: BodyType<TokenRefreshRequestRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: BodyType<TokenRefreshRequestRequest>},
        TContext
      > => {

      const mutationOptions = getRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listUsers = (
    params?: MaybeRef<ListUsersParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<TeamUserList[]>(
      {url: `http://localhost:8000/api/accounts/users/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListUsersQueryKey = (params?: MaybeRef<ListUsersParams>,) => {
    return [
    'http:','localhost:8000','api','accounts','users', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListUsersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> 
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListUsersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const getUser = (
    id: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<User>(
      {url: `http://localhost:8000/api/accounts/users/${id}/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','accounts','users',id
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetUserQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> 
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>



export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<ErrorResponseNotAuthenticated | ErrorResponseNotFound>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




