/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  SchemaRetrieve200Four,
  SchemaRetrieve200One,
  SchemaRetrieve200Three,
  SchemaRetrieve200Two,
  SchemaRetrieveParams
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.

- YAML: application/vnd.oai.openapi
- JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = (
    params?: MaybeRef<SchemaRetrieveParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<SchemaRetrieve200One | SchemaRetrieve200Two | SchemaRetrieve200Three | SchemaRetrieve200Four>(
      {url: `http://localhost:8000/api/schema/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getSchemaRetrieveQueryKey = (params?: MaybeRef<SchemaRetrieveParams>,) => {
    return [
    'http:','localhost:8000','api','schema', ...(params ? [params]: [])
    ] as const;
    }

    
export const getSchemaRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof schemaRetrieve>>, TError = ErrorType<unknown>>(params?: MaybeRef<SchemaRetrieveParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getSchemaRetrieveQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof schemaRetrieve>>> = ({ signal }) => schemaRetrieve(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof schemaRetrieve>>, TError, TData> 
}

export type SchemaRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof schemaRetrieve>>>
export type SchemaRetrieveQueryError = ErrorType<unknown>



export function useSchemaRetrieve<TData = Awaited<ReturnType<typeof schemaRetrieve>>, TError = ErrorType<unknown>>(
 params?: MaybeRef<SchemaRetrieveParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof schemaRetrieve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSchemaRetrieveQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




