/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  ListAdminUserPointsTransactionsParams,
  ListMyPointsTransactionsParams,
  PaginatedPointsTransactionList
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getAdminUserPointsBalance = (
    userId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      userId = unref(userId);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/points/admin/users/${userId}/balance/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAdminUserPointsBalanceQueryKey = (userId?: MaybeRef<number>,) => {
    return [
    'http:','localhost:8000','api','points','admin','users',userId,'balance'
    ] as const;
    }

    
export const getGetAdminUserPointsBalanceQueryOptions = <TData = Awaited<ReturnType<typeof getAdminUserPointsBalance>>, TError = ErrorType<unknown>>(userId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUserPointsBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetAdminUserPointsBalanceQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminUserPointsBalance>>> = ({ signal }) => getAdminUserPointsBalance(userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(userId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminUserPointsBalance>>, TError, TData> 
}

export type GetAdminUserPointsBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminUserPointsBalance>>>
export type GetAdminUserPointsBalanceQueryError = ErrorType<unknown>



export function useGetAdminUserPointsBalance<TData = Awaited<ReturnType<typeof getAdminUserPointsBalance>>, TError = ErrorType<unknown>>(
 userId: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUserPointsBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminUserPointsBalanceQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const modifyUserPointsBalance = (
    userId: MaybeRef<number>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      userId = unref(userId);
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/points/admin/users/${userId}/modify/`, method: 'POST', signal
    },
      options);
    }
  


export const getModifyUserPointsBalanceMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof modifyUserPointsBalance>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof modifyUserPointsBalance>>, TError,{userId: number}, TContext> => {

const mutationKey = ['modifyUserPointsBalance'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof modifyUserPointsBalance>>, {userId: number}> = (props) => {
          const {userId} = props ?? {};

          return  modifyUserPointsBalance(userId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ModifyUserPointsBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof modifyUserPointsBalance>>>
    
    export type ModifyUserPointsBalanceMutationError = ErrorType<unknown>

    export const useModifyUserPointsBalance = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof modifyUserPointsBalance>>, TError,{userId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof modifyUserPointsBalance>>,
        TError,
        {userId: number},
        TContext
      > => {

      const mutationOptions = getModifyUserPointsBalanceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listAdminUserPointsTransactions = (
    userId: MaybeRef<number>,
    params?: MaybeRef<ListAdminUserPointsTransactionsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      userId = unref(userId);
params = unref(params);
      
      return customInstance<PaginatedPointsTransactionList>(
      {url: `http://localhost:8000/api/points/admin/users/${userId}/transactions/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListAdminUserPointsTransactionsQueryKey = (userId?: MaybeRef<number>,
    params?: MaybeRef<ListAdminUserPointsTransactionsParams>,) => {
    return [
    'http:','localhost:8000','api','points','admin','users',userId,'transactions', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAdminUserPointsTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof listAdminUserPointsTransactions>>, TError = ErrorType<unknown>>(userId: MaybeRef<number>,
    params?: MaybeRef<ListAdminUserPointsTransactionsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUserPointsTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListAdminUserPointsTransactionsQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminUserPointsTransactions>>> = ({ signal }) => listAdminUserPointsTransactions(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(userId))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAdminUserPointsTransactions>>, TError, TData> 
}

export type ListAdminUserPointsTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof listAdminUserPointsTransactions>>>
export type ListAdminUserPointsTransactionsQueryError = ErrorType<unknown>



export function useListAdminUserPointsTransactions<TData = Awaited<ReturnType<typeof listAdminUserPointsTransactions>>, TError = ErrorType<unknown>>(
 userId: MaybeRef<number>,
    params?: MaybeRef<ListAdminUserPointsTransactionsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdminUserPointsTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAdminUserPointsTransactionsQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const getMyPointsBalance = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `http://localhost:8000/api/points/balance/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyPointsBalanceQueryKey = () => {
    return [
    'http:','localhost:8000','api','points','balance'
    ] as const;
    }

    
export const getGetMyPointsBalanceQueryOptions = <TData = Awaited<ReturnType<typeof getMyPointsBalance>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPointsBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetMyPointsBalanceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPointsBalance>>> = ({ signal }) => getMyPointsBalance(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyPointsBalance>>, TError, TData> 
}

export type GetMyPointsBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getMyPointsBalance>>>
export type GetMyPointsBalanceQueryError = ErrorType<unknown>



export function useGetMyPointsBalance<TData = Awaited<ReturnType<typeof getMyPointsBalance>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPointsBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyPointsBalanceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const listMyPointsTransactions = (
    params?: MaybeRef<ListMyPointsTransactionsParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedPointsTransactionList>(
      {url: `http://localhost:8000/api/points/transactions/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListMyPointsTransactionsQueryKey = (params?: MaybeRef<ListMyPointsTransactionsParams>,) => {
    return [
    'http:','localhost:8000','api','points','transactions', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListMyPointsTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof listMyPointsTransactions>>, TError = ErrorType<unknown>>(params?: MaybeRef<ListMyPointsTransactionsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyPointsTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListMyPointsTransactionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyPointsTransactions>>> = ({ signal }) => listMyPointsTransactions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyPointsTransactions>>, TError, TData> 
}

export type ListMyPointsTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof listMyPointsTransactions>>>
export type ListMyPointsTransactionsQueryError = ErrorType<unknown>



export function useListMyPointsTransactions<TData = Awaited<ReturnType<typeof listMyPointsTransactions>>, TError = ErrorType<unknown>>(
 params?: MaybeRef<ListMyPointsTransactionsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyPointsTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyPointsTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




