/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  DigitalInventoryItem,
  EquipDigitalItem,
  ErrorResponseNotAuthenticated,
  ErrorResponseNotFound,
  ErrorResponseValidationError,
  ListMyDigitalInventoryParams,
  PaginatedDigitalInventoryItemList
} from '../.ts.schemas';

import { customInstance } from '../../lib/apiClient';
import type { ErrorType , BodyType } from '../../lib/apiClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const equipDigitalInventoryItem = (
    equipDigitalItem: MaybeRef<EquipDigitalItem>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      equipDigitalItem = unref(equipDigitalItem);
      
      return customInstance<DigitalInventoryItem>(
      {url: `http://localhost:8000/api/inventory/equip/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: equipDigitalItem, signal
    },
      options);
    }
  


export const getEquipDigitalInventoryItemMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof equipDigitalInventoryItem>>, TError,{data: BodyType<EquipDigitalItem>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof equipDigitalInventoryItem>>, TError,{data: BodyType<EquipDigitalItem>}, TContext> => {

const mutationKey = ['equipDigitalInventoryItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof equipDigitalInventoryItem>>, {data: BodyType<EquipDigitalItem>}> = (props) => {
          const {data} = props ?? {};

          return  equipDigitalInventoryItem(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EquipDigitalInventoryItemMutationResult = NonNullable<Awaited<ReturnType<typeof equipDigitalInventoryItem>>>
    export type EquipDigitalInventoryItemMutationBody = BodyType<EquipDigitalItem>
    export type EquipDigitalInventoryItemMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useEquipDigitalInventoryItem = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof equipDigitalInventoryItem>>, TError,{data: BodyType<EquipDigitalItem>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof equipDigitalInventoryItem>>,
        TError,
        {data: BodyType<EquipDigitalItem>},
        TContext
      > => {

      const mutationOptions = getEquipDigitalInventoryItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const listMyDigitalInventory = (
    params?: MaybeRef<ListMyDigitalInventoryParams>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      params = unref(params);
      
      return customInstance<PaginatedDigitalInventoryItemList>(
      {url: `http://localhost:8000/api/inventory/my/`, method: 'GET',
        params: unref(params), signal
    },
      options);
    }
  



export const getListMyDigitalInventoryQueryKey = (params?: MaybeRef<ListMyDigitalInventoryParams>,) => {
    return [
    'http:','localhost:8000','api','inventory','my', ...(params ? [params]: [])
    ] as const;
    }

    
export const getListMyDigitalInventoryQueryOptions = <TData = Awaited<ReturnType<typeof listMyDigitalInventory>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(params?: MaybeRef<ListMyDigitalInventoryParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyDigitalInventory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListMyDigitalInventoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyDigitalInventory>>> = ({ signal }) => listMyDigitalInventory(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyDigitalInventory>>, TError, TData> 
}

export type ListMyDigitalInventoryQueryResult = NonNullable<Awaited<ReturnType<typeof listMyDigitalInventory>>>
export type ListMyDigitalInventoryQueryError = ErrorType<ErrorResponseNotAuthenticated>



export function useListMyDigitalInventory<TData = Awaited<ReturnType<typeof listMyDigitalInventory>>, TError = ErrorType<ErrorResponseNotAuthenticated>>(
 params?: MaybeRef<ListMyDigitalInventoryParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyDigitalInventory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyDigitalInventoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




export const unequipDigitalInventoryItem = (
    equipDigitalItem: MaybeRef<EquipDigitalItem>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      equipDigitalItem = unref(equipDigitalItem);
      
      return customInstance<DigitalInventoryItem>(
      {url: `http://localhost:8000/api/inventory/unequip/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: equipDigitalItem, signal
    },
      options);
    }
  


export const getUnequipDigitalInventoryItemMutationOptions = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unequipDigitalInventoryItem>>, TError,{data: BodyType<EquipDigitalItem>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof unequipDigitalInventoryItem>>, TError,{data: BodyType<EquipDigitalItem>}, TContext> => {

const mutationKey = ['unequipDigitalInventoryItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unequipDigitalInventoryItem>>, {data: BodyType<EquipDigitalItem>}> = (props) => {
          const {data} = props ?? {};

          return  unequipDigitalInventoryItem(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnequipDigitalInventoryItemMutationResult = NonNullable<Awaited<ReturnType<typeof unequipDigitalInventoryItem>>>
    export type UnequipDigitalInventoryItemMutationBody = BodyType<EquipDigitalItem>
    export type UnequipDigitalInventoryItemMutationError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>

    export const useUnequipDigitalInventoryItem = <TError = ErrorType<ErrorResponseValidationError | ErrorResponseNotAuthenticated | ErrorResponseNotFound>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unequipDigitalInventoryItem>>, TError,{data: BodyType<EquipDigitalItem>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof unequipDigitalInventoryItem>>,
        TError,
        {data: BodyType<EquipDigitalItem>},
        TContext
      > => {

      const mutationOptions = getUnequipDigitalInventoryItemMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    