# Generated by Django 5.2.12 on 2026-04-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='location',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='team_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
